'use strict';
// Real Chromium, intercepted Join requests, synthetic Tasker bridge only.
const assert=require('node:assert/strict'), fs=require('node:fs'), path=require('node:path'), http=require('node:http'), cp=require('node:child_process');
const modules=process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES || '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(path.join(modules,'playwright'));
const ROOT=path.resolve(__dirname,'..'), results=[], unexpected=[];
const KEY='fixture_join_private_key_12345678', DEVICE='a'.repeat(32);
const bundle=cp.execFileSync('python3',['-c','import xml.etree.ElementTree as E,sys;print(next(E.parse(sys.argv[1]).getroot().iter("WebElement")).findtext(\'Str[@sr="arg2"]\'))',path.join(ROOT,'tasker/Santa_Fe_Direct.prj.xml')],{maxBuffer:1000000}).toString();
const server=http.createServer((req,res)=>{
  const name=new URL(req.url,'http://localhost').pathname;
  if(name==='/bundle'){res.writeHead(200,{'content-type':'text/html'});res.end(bundle);return;}
  if(!['index.html','control.css','control.js','protocol.js'].some(file=>name==='/'+file)){res.writeHead(404);res.end();return;}
  const file=path.join(ROOT,'control',name.slice(1));res.writeHead(200,{'content-type':name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'});res.end(fs.readFileSync(file));
});
let browser, origin;
async function scenario(name,fn){try{await fn();results.push({test:name,passed:true});}catch(e){results.push({test:name,passed:false,error:e.message});process.stderr.write(name+': '+e.message+'\n');}}
async function fixture(options={}){
  const context=await browser.newContext({viewport:options.desktop?{width:1280,height:900}:{width:412,height:915},acceptDownloads:true});
  const page=await context.newPage(), calls=[], errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',async route=>{
    const request=route.request();if(request.url().startsWith(origin+'/'))return route.continue();
    if(!request.url().startsWith('https://joinjoaomgcd.appspot.com/_ah/api/messaging/v1/sendPush?')){unexpected.push(request.url());return route.abort();}
    calls.push({url:request.url(),method:request.method()});
    if(options.delay)await new Promise(resolve=>{options.release=resolve;});
    if(options.abort)return route.abort('failed');
    return route.fulfill({status:options.http || 200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:options.text || JSON.stringify(options.body || {success:true})});
  });
  if(options.storedLog!==undefined)await page.addInitScript({content:'localStorage.setItem("santa-fe.join.log.v1",'+JSON.stringify(JSON.stringify(options.storedLog))+')'});
  if(options.blockStorage)await page.addInitScript({content:'Storage.prototype.setItem=function(){throw new Error("blocked")};'});
  if(options.native)await page.addInitScript({content:`
    window.__calls=[];window.__reads=[];window.__snapshot={version:1,busy:false,pending:false,doors:'Locked',engine:'Off',climate:'Off',vehicleTime:'2026-10-05T19:00:00Z',statusReadAt:1791237000000,vehicle:'VIN ending 0001',carLat:'0.0',carLon:'0.0',carTime:'2026-10-05T19:00:00Z',distance:'0',phoneAccuracy:'15',proximity:'Near',presets:{regular:'72 F / 10 min',cold:'64 F / 6 min',hot:'80 F / 9 min'},result:{id:'',time:1791237000000,state:'READ',message:'Saved phone result'}};window.__log=[];
    window.tk={global(name){window.__reads.push(name);if(name==='SFDWebState')return JSON.stringify(window.__snapshot);if(name==='SFDWebLog')return JSON.stringify(window.__log);throw new Error('Unexpected global read');},performTask(task,priority,payload){window.__calls.push({task,priority,payload});if(task==='SFD Web Receive'){const p=payload.split('|');window.__snapshot.busy=true;setTimeout(()=>{window.__snapshot.busy=false;window.__snapshot.result={id:p[1],time:Date.now(),state:p[0]==='ping'?'PHONE REACHED':'SUCCESS',message:p[0]==='ping'?'Phone test received. No Hyundai request.':'Hyundai confirmed completion.'};window.__log.push({command:p[0],state:window.__snapshot.result.state,time:Date.now(),message:window.__snapshot.result.message});},60);}return true;}};
  `});
  await page.goto(origin+(options.bundle?'/bundle':'/index.html'));await page.waitForFunction(()=>document.querySelector('#notice').textContent.length>0);
  return {context,page,calls,errors,async close(){assert.deepEqual(errors,[]);await context.close();}};
}
async function configure(f){await f.page.click('[data-tab=settings]');await f.page.fill('#device-id',DEVICE);await f.page.fill('#api-key',KEY);await f.page.click('button[type=submit]');await f.page.click('[data-tab=controls]');}
async function action(f,command,accept=true){await f.page.click('[data-tab=controls]');await f.page.click('[data-command='+command+']');if(accept){if(command.startsWith('ignition_on'))await f.page.check('#safe');await f.page.click('#confirm-send');}else await f.page.locator('#confirmation button[value=cancel]').click();}
async function sent(f){await f.page.waitForFunction(()=>document.getElementById('last-state').textContent==='SENT');}
async function main(){
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
  let executablePath=process.env.SANTAFE_CHROMIUM,args=['--no-sandbox'];
  if(process.env.SFD_BROWSER_MODULE){const chrome=require(process.env.SFD_BROWSER_MODULE);executablePath=await chrome.executablePath();args=chrome.args;}
  browser=await chromium.launch({headless:true,executablePath,args});
  await scenario('mobile compact layout and empty account have no network',async()=>{const f=await fixture();assert.equal(f.calls.length,0);assert.equal(await f.page.locator('#settings').isVisible(),true);assert.equal(await f.page.locator('[data-command=lock]').isDisabled(),true);assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await f.close();});
  await scenario('Join settings persist across reload while secret field stays blank',async()=>{const f=await fixture();await configure(f);await f.page.reload();await f.page.click('[data-tab=settings]');assert.equal(await f.page.inputValue('#api-key'),'');assert.equal(await f.page.inputValue('#device-id'),DEVICE);assert.equal(await f.page.locator('[data-command=ping]').isEnabled(),true);assert.equal(f.calls.length,0);await f.close();});
  await scenario('full Join link imports privately without echoing it',async()=>{const f=await fixture();await f.page.fill('#join-link','https://joinjoaomgcd.appspot.com/_ah/api/messaging/v1/sendPush?text=hyundai=:=lock&deviceId='+DEVICE+'&&apikey='+KEY);await f.page.click('button[type=submit]');assert.equal(await f.page.inputValue('#join-link'),'');assert.equal(await f.page.inputValue('#api-key'),'');assert.ok(!(await f.page.textContent('body')).includes(KEY));assert.equal(f.calls.length,0);await f.close();});
  await scenario('connection test sends one correct Join push and never claims vehicle success',async()=>{const f=await fixture();await configure(f);await f.page.click('[data-tab=settings]');await f.page.click('[data-command=ping]');await sent(f);assert.equal(f.calls.length,1);const u=new URL(f.calls[0].url);assert.ok(u.searchParams.get('text').startsWith('hyundai=:=ping|'));assert.equal(u.searchParams.get('deviceId'),DEVICE);assert.equal(f.calls[0].method,'GET');assert.match(await f.page.textContent('#last-message'),/Check Tasker/);assert.equal(await f.page.textContent('#doors'),'Unknown');await f.close();});
  await scenario('all six confirmed controls send exactly one allowlisted command',async()=>{const f=await fixture();await configure(f);for(const command of ['ignition_on','ignition_on_cold','ignition_on_hot','ignition_off','lock','unlock']){const before=f.calls.length;await action(f,command);await sent(f);assert.equal(f.calls.length,before+1);const payload=new URL(f.calls.at(-1).url).searchParams.get('text').slice(10).split('|');assert.equal(payload[0],command);assert.match(payload[1],/^[0-9a-f]{32}$/);assert.equal(payload[3],command.startsWith('ignition_on')?'1':'0');}await f.close();});
  await scenario('start checkbox and cancelled controls send nothing',async()=>{const f=await fixture();await configure(f);await f.page.click('[data-command=ignition_on]');assert.equal(await f.page.locator('#confirm-send').isDisabled(),true);await f.page.locator('#confirmation button[value=cancel]').click();await action(f,'unlock',false);assert.equal(f.calls.length,0);await f.close();});
  await scenario('rapid taps are blocked while one Join request is running',async()=>{const opts={delay:true},f=await fixture(opts);await configure(f);await action(f,'lock');await f.page.waitForFunction(()=>document.getElementById('last-state').textContent==='SENDING');await f.page.locator('[data-command=unlock]').evaluate(el=>el.click());assert.equal(f.calls.length,1);assert.equal(await f.page.locator('[data-command=unlock]').isDisabled(),true);opts.release();await sent(f);await f.close();});
  await scenario('unknown delivery persists across reload without a retry',async()=>{const f=await fixture({abort:true});await configure(f);await action(f,'lock');await f.page.waitForFunction(()=>document.getElementById('last-state').textContent==='UNKNOWN');assert.equal(f.calls.length,1);await f.page.reload();await f.page.click('[data-tab=controls]');assert.equal(f.calls.length,1);assert.equal(await f.page.locator('[data-command=unlock]').isDisabled(),true);await f.page.click('#acknowledge');assert.equal(await f.page.locator('[data-command=unlock]').isEnabled(),true);await f.close();});
  await scenario('Join API rejection and exported logs omit secret errors',async()=>{const f=await fixture({body:{success:false,errorMessage:KEY,requestUrl:DEVICE}});await configure(f);await action(f,'lock');await f.page.waitForFunction(()=>document.getElementById('last-state').textContent==='REJECTED');await f.page.click('[data-tab=log]');const [download]=await Promise.all([f.page.waitForEvent('download'),f.page.click('#export-log')]);const text=fs.readFileSync(await download.path(),'utf8');assert.ok(!text.includes(KEY)&&!text.includes(DEVICE));assert.match(text,/REJECTED/);assert.ok(!(await f.page.textContent('body')).includes(KEY));await f.close();});
  await scenario('blocked storage prevents sending and malformed stored log is tolerated',async()=>{const f=await fixture({blockStorage:true,storedLog:null});await f.page.uncheck('#remember');await configure(f);await action(f,'lock');assert.equal(f.calls.length,0);assert.match(await f.page.textContent('#notice'),/cannot save/);await f.close();});
  await scenario('packaged HTML renders offline and reads only the two safe Tasker variables',async()=>{const f=await fixture({native:true,bundle:true});assert.equal(await f.page.textContent('#mode'),'Tasker phone interface');assert.equal(await f.page.textContent('#doors'),'Locked');assert.equal(await f.page.textContent('#preset-cold'),'64 F / 6 min');assert.equal(await f.page.textContent('#car-coordinates'),'0.0, 0.0');assert.equal(f.calls.length,0);const names=await f.page.evaluate(()=>window.__reads);assert.deepEqual(new Set(names),new Set(['SFDWebState','SFDWebLog']));fs.mkdirSync(path.join(ROOT,'docs/verification'),{recursive:true});await f.page.screenshot({path:path.join(ROOT,'docs/verification/controller-phone.png'),fullPage:true});await f.close();});
  await scenario('phone WebView routes command once and displays the correlated vehicle result',async()=>{const f=await fixture({native:true,bundle:true});await action(f,'ignition_on_cold');await f.page.waitForFunction(()=>document.getElementById('last-state').textContent==='SUCCESS');const calls=await f.page.evaluate(()=>window.__calls);assert.equal(calls.length,1);assert.equal(calls[0].task,'SFD Web Receive');assert.ok(calls[0].payload.startsWith('ignition_on_cold|'));assert.equal(f.calls.length,0);assert.equal(await f.page.textContent('#doors'),'Locked');assert.equal(await f.page.locator('[data-command=unlock]').isEnabled(),true);await f.close();});
  await scenario('phone settings buttons call only named native editors',async()=>{const f=await fixture({native:true,bundle:true});await f.page.click('[data-tab=settings]');await f.page.click('[data-task="SFD Cold Settings"]');const calls=await f.page.evaluate(()=>window.__calls);assert.deepEqual(calls,[{task:'SFD Cold Settings',priority:6,payload:''}]);assert.equal(f.calls.length,0);await f.close();});
  await scenario('desktop layout and text-only log resist HTML injection',async()=>{const f=await fixture({desktop:true,storedLog:[{time:Date.now(),command:'lock',state:'FAILED',message:'<img src=x onerror=window.bad=true>'}]});await f.page.click('[data-tab=log]');assert.equal(await f.page.evaluate(()=>window.bad),undefined);assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await f.close();});
  assert.deepEqual(unexpected,[],'no requests to Hyundai or an unexpected origin');
}
main().catch(e=>{process.stderr.write(e.stack+'\n');process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();const report={passed:results.every(r=>r.passed)&&results.length===14,scenarios:results.length,real_join_requests:false,real_hyundai_requests:false,results};fs.mkdirSync(path.join(ROOT,'docs/verification'),{recursive:true});fs.writeFileSync(path.join(ROOT,'docs/verification/controller-browser.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(!report.passed)process.exitCode=1;});
