'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),bytes=fs.readFileSync(path.join(root,'zork/data/zork1.z3'));
const Machine=vm.runInThisContext(fs.readFileSync(path.join(root,'zork/vendor/zvm.js'),'utf8')+'; ZVM;');
const Engine=require('../zork/engine'),View=require('../zork/view'),meta=require('../zork/data/objects.json');
function game(){const e=new Engine(Machine,bytes),v=new View(e,meta);let text='';e.onupdate=t=>{text=t;v.update(t);};e.start();return {e,v,get text(){return text;},send:c=>e.send(c)};}
const names=items=>items.map(o=>o.name);
const kitchen=['north','east','open window','enter window'];
const room=g=>g.e.state().name;
const ram=e=>Buffer.from(e.vm.ram.getUint8Array(0,e.vm.staticmem));

test('original story bytes, edition and checksum',()=>{assert.equal(bytes.length,86838);assert.equal(bytes[0],3);assert.equal(bytes.readUInt16BE(2),119);assert.equal(bytes.subarray(18,24).toString(),'880429');assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),'37084966477dff679282de42974b2077156b1bd68fad92a65d4ea94d8eb64d79');});
test('original opening and all 250 objects are intact',()=>{const g=game();assert.match(g.text,/standing in an open field west of a white house/);assert.match(g.text,/Release 119 \/ Serial number 880429/);assert.equal(g.e.objects().length,250);assert.equal(room(g),'West of House');assert.equal(g.e.state().moves,0);assert(!names(g.v.current.here).includes('leaflet'));});
test('mailbox, reading and original inventory',()=>{const g=game();g.send('open mailbox');assert.match(g.text,/reveals a leaflet/);assert(names(g.v.current.here).includes('leaflet'));g.send('take leaflet');assert(names(g.v.current.inventory).includes('leaflet'));g.send('read leaflet');assert.match(g.text,/WELCOME TO ZORK!/);g.send('inventory');assert.match(g.text,/leaflet/);});
test('closed opaque sack does not expose its contents',()=>{const g=game();kitchen.forEach(g.send);assert.equal(room(g),'Kitchen');assert(!names(g.v.current.here).includes('clove of garlic'));g.send('take sack');assert(!names(g.v.current.inventory).includes('clove of garlic'));g.send('open sack');assert(names(g.v.current.inventory).includes('clove of garlic'));});
test('trapdoor is invisible until original rug puzzle reveals it',()=>{const g=game();[...kitchen,'west'].forEach(g.send);assert.equal(room(g),'Living Room');assert(!names(g.v.current.here).includes('trap door'));g.send('move rug');assert(names(g.v.current.here).includes('trap door'));g.send('open trap door');g.send('down');assert.match(g.text,/pitch black/);assert.equal(g.v.current.here.length,0);assert(g.v.current.dark);});
test('turning on the actual lamp restores visibility',()=>{const g=game();[...kitchen,'west','take lamp','move rug','open trap door','down'].forEach(g.send);assert(g.v.current.dark);g.send('turn on lamp');assert(!g.v.current.dark);assert.match(g.text,/Cellar/);});
test('GUI refresh never changes dynamic memory, PC, stack, score or moves',()=>{const g=game();g.send('open mailbox');const before={ram:ram(g.e),pc:g.e.vm.pc,stack:JSON.stringify(g.e.vm.frames),state:g.e.state()};for(let i=0;i<50;i++){g.v.update();g.e.objects();g.e.state();}assert.deepEqual(ram(g.e),before.ram);assert.equal(g.e.vm.pc,before.pc);assert.equal(JSON.stringify(g.e.vm.frames),before.stack);assert.deepEqual(g.e.state(),before.state);});
test('snapshot is read-only and resumes exact prompt state',()=>{const g=game();[...kitchen,'west','take lamp','take sword'].forEach(g.send);const before=ram(g.e),state=g.e.state(),snap=g.e.snapshot();assert.deepEqual(ram(g.e),before);g.send('east');assert.equal(room(g),'Kitchen');g.e.restore(snap);assert.deepEqual(g.e.state(),state);assert.deepEqual(ram(g.e),before);g.send('look');assert.match(g.text,/Living Room/);});
test('native SAVE and RESTORE use original opcodes and Quetzal',()=>{const g=game();let saved;g.e.onclosefile=str=>{if(str.mode===1)saved=structuredClone(str.bytes);};g.send('open mailbox');const state=g.e.state();g.send('save');assert.equal(g.e.pending.type,'file');g.e.file({name:'1'});assert.equal(Buffer.from(saved).subarray(0,4).toString(),'FORM');assert.match(g.text,/Ok\./);g.send('north');g.send('restore');g.e.file({name:'1',bytes:saved});assert.deepEqual(g.e.state(),state);g.send('take leaflet');assert.match(g.text,/Taken/);});
test('cancelling SAVE and RESTORE returns to the original parser',()=>{const g=game();for(const c of ['save','restore']){g.send(c);g.e.file(null);assert.equal(g.e.pending.type,'line');assert.match(g.text,/Failed/);}g.send('look');assert.match(g.text,/West of House/);});
test('bad resume signatures are rejected without touching memory',()=>{const g=game(),before=ram(g.e),bad=g.e.snapshot();bad.signature='wrong';assert.throws(()=>g.e.restore(bad),/does not belong/);assert.deepEqual(ram(g.e),before);});
test('native quit and confirmation are handled by the original game',()=>{const g=game();g.send('quit');assert.match(g.text,/leave the game/);g.send('yes');assert(g.e.ended);});
test('original parser rejects unknown words instead of inventing actions',()=>{const g=game();g.send('teleport to mordor');assert.match(g.text,/don't know the word/);assert.equal(room(g),'West of House');});
