(function(){
'use strict';
const C=FlowCore,Z=FlowZip,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='flowcraft:v1:project',CONSENT='flowcraft:v1:remember';
let project=C.recipe('hello'),selected='Email_me_the_result',tab='recipes',query='',advanced=false,showAllTemplates=false,showAllSteps=false,dirty=false,insertion=null,history=[],future=[],pending=new Set(),remember=false,toastTimer,referenceTarget=null,modalReturnFocus=null;
try{remember=localStorage.getItem(CONSENT)==='yes';if(remember){const saved=localStorage.getItem(STORE);if(saved&&saved.length<25*1024*1024){project=C.assertProject(JSON.parse(saved));selected=Object.keys(project.definition.actions).at(-1)||'$trigger';}}}catch{remember=false;}
function notify(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),6000);}
function persist(){if(remember){try{localStorage.setItem(STORE,JSON.stringify(project));$('saveState').textContent='Saved in this browser';}catch{$('saveState').textContent='Browser storage full: save a project file';}}else $('saveState').textContent=dirty?'Unsaved to disk · this session only':'This session only';}
function mutate(fn,full=true){const before=C.clone(project);try{fn();history.push(before);if(history.length>40)history.shift();future=[];dirty=true;persist();if(full)render();else{renderTree();renderChecks();}}catch(e){project=before;notify(e.message);}}
function undo(){if(!history.length)return;future.push(C.clone(project));project=history.pop();pending.clear();dirty=true;persist();render();}
function redo(){if(!future.length)return;history.push(C.clone(project));project=future.pop();pending.clear();dirty=true;persist();render();}
function getSelected(){if(selected==='$trigger')return {name:Object.keys(project.definition.triggers)[0],a:Object.values(project.definition.triggers)[0],trigger:true};return C.locate(project,selected);}
function select(name){if(pending.size&&!confirm('Discard the invalid field edit and select another step? The last valid value will be kept.'))return;selected=name;insertion=null;pending.clear();renderTree();renderInspector();$('inspector').classList.add('open');}
function title(n){return project.labels[n]||n.replace(/_/g,' ');}
const PLAIN_RECIPES={
 hello:['Send myself a test email','The easiest first flow. Click a button and get an email.'],
 summary:['Summarize new emails with AI','When a matching email arrives, ask AI to summarize it and email the answer to you.'],
 attachments:['Save email attachments','When a matching email arrives, save its attachments to OneDrive.'],
 digest:['Email me a morning inbox summary','At a set time each day, find recent emails and send yourself a simple table.'],
 records:['Turn a list into an email report','Keep the items you want, make a table, and email it.'],
 perItem:['Ask AI about every item in a list','Go through a list one item at a time, ask AI about each item, and email all the answers.'],
 routing:['Only act when something matches','Check an email. If it matches your rule, do something.'],
 catch:['Tell me if something breaks','Run a group of steps and email you only if something fails.'],
 blank:['Build my own flow','Start empty and choose what starts the flow and what happens next.']
};
const PLAIN_STEPS={
 compose:['Keep some information','Save text, a number, a list, or another value so a later step can use it.'],
 parse:['Read structured information','Turn structured text into separate pieces you can use later.'],
 filter:['Keep only matching items','Start with a list and keep only the items that match your rule.'],
 select:['Pick details from a list','Choose which details you want to keep from every item.'],
 join:['Turn a list into text','Combine a list into one piece of text.'],
 table:['Make a table','Turn a list into a table you can put in an email.'],
 initialize:['Create a saved value','Create a named place to remember something while the flow runs.'],
 set:['Change a saved value','Replace something the flow is remembering.'],
 appendText:['Add more text','Add text to something the flow is already remembering.'],
 appendArray:['Add something to a list','Add one new item to a saved list.'],
 increment:['Increase a number','Add to a number the flow is remembering.'],
 loop:['Do this for every item','Repeat the steps inside this box for each item in a list.'],
 condition:['Make a yes or no decision','Check a rule, then do one thing if yes and another if no.'],
 scope:['Keep steps together','Put several steps together as one group.'],
 delay:['Wait','Pause before continuing.'],
 stop:['Stop here','End the flow here.'],
 email:['Send an email','Send an email with Outlook.'],
 getEmail:['Open an email','Load one email so later steps can use it.'],
 listEmail:['Find emails','Find a group of emails in Outlook.'],
 attachment:['Open an email attachment','Load one attachment from an email.'],
 outlookHttp:['Special Outlook request','Use an advanced Outlook request.'],
 htmlText:['Turn an email into plain text','Remove email formatting so the words are easier to work with.'],
 teams:['Send a Teams message','Send someone a message in Microsoft Teams.'],
 saveFile:['Save a file to OneDrive','Create a file in OneDrive for Business.'],
 readFile:['Open a OneDrive file','Read the contents of a file in OneDrive.'],
 sharepoint:['Read a SharePoint list','Get items from a SharePoint list.'],
 ai:['Ask AI','Send information to one of your saved AI prompts and use the answer.'],
 http:['Connect to a web service','Send a request to a web address.'],
 response:['Reply to a web request','Send an answer back to the app or service that called this flow.']
};
const PLAIN_TRIGGERS={
 manual:['When I click a button','Start only when you manually run the flow.'],
 mail:['When a new email arrives','Start when Outlook receives an email that matches your choices.'],
 schedule:['At a scheduled time','Start automatically on the schedule you choose.'],
 request:['When another app calls this flow','Start when another app sends this flow a web request.'],
 unknown:['Custom starting event','This starting event came from an imported flow.']
};
const PLAIN_GROUPS={'Data':'Work with information','Variables':'Remember information','Logic':'Repeat or decide','Outlook':'Email','Microsoft 365':'Microsoft apps','AI':'AI','Advanced':'Advanced tools'};
const PLAIN_LABELS={
 'Write a welcome message':'Create the message',
 'Email me the result':'Send me the email',
 'Read the email text':'Read the email',
 'Summarize the email':'Ask AI to summarize it',
 'Ignore inline signature images':'Ignore signature images',
 'For each attachment':'For each attachment',
 'Get the file':'Open the attachment',
 'Save to OneDrive':'Save it to OneDrive',
 'Find today’s messages':'Find today’s emails',
 'Choose email fields':'Pick the details to include',
 'Build the digest table':'Make the summary table',
 'Send the digest':'Send the summary email',
 'My records':'Your list',
 'Keep open records':'Keep only open items',
 'Make the report':'Make the table',
 'Email the report':'Send the report',
 'Create results list':'Create an empty results list',
 'Analyze one record at a time':'For each item',
 'Analyze this record':'Ask AI about this item',
 'Collect the result':'Save the AI answer',
 'Make the results table':'Make the results table',
 'Email all results':'Send the results',
 'Is this urgent?':"Does the subject say 'urgent'?",
 'Notify me':'Send me an email',
 'No notification needed':'Do nothing',
 'Work to protect':'Try these steps',
 'Replace this with your work':'Put your main steps here',
 'If the work fails':'If something goes wrong',
 'Tell me what failed':'Email me about the problem'
};
const COMMON_STEPS=new Set(['compose','filter','select','table','loop','condition','delay','email','getEmail','listEmail','attachment','htmlText','teams','saveFile','readFile','sharepoint','ai']);
function recipeCopy(r){return PLAIN_RECIPES[r.id]||[r.title,r.desc];}
function stepCopy(c){return PLAIN_STEPS[c.id]||[c.title,c.description];}
function triggerCopy(k){return PLAIN_TRIGGERS[k]||[C.triggers[k]?.title||'Start the flow',C.triggers[k]?.description||'Choose when this flow should start.'];}
function groupCopy(g){return PLAIN_GROUPS[g]||g;}
function nodeTitle(name,a){const raw=title(name);return PLAIN_LABELS[raw]||raw||stepCopy(C.catalog[C.kind(a)]||{id:'unknown',title:'Imported step',description:''})[0];}
function branchCopy(label){return label==='Yes'?'If yes':label==='Otherwise'?'If no':label==='Steps'?'Do these steps':label;}
function fieldCopy(kind,label){
 const map={
  'compose:Value':'What should this step remember?',
  'parse:JSON to read':'What information should I read?',
  'parse:Expected structure':'What does that information look like?',
  'filter:List':'Which list should I check?',
  'filter:Keep item when':'Which items should I keep?',
  'select:List':'Which list should I use?',
  'select:Fields to keep':'Which details should each item include?',
  'join:List':'Which list should I combine?',
  'join:Separator':'What should go between the items?',
  'table:List of records':'Which list should become a table?',
  'initialize:Variable name':'What should I call this saved value?',
  'initialize:Type':'What kind of information is it?',
  'initialize:Starting value':'What should it start with?',
  'set:Variable':'Which saved value should I change?',
  'set:New value':'What should it become?',
  'appendText:Text variable':'Which saved text should I add to?',
  'appendText:Text to add':'What text should I add?',
  'appendArray:Array variable':'Which saved list should I add to?',
  'appendArray:Item to add':'What should I add?',
  'increment:Counter variable':'Which saved number should I change?',
  'increment:Increase by':'How much should I add?',
  'loop:Repeat for each item in':'Which list should I go through?',
  'loop:Items at the same time':'How many items should run at once?',
  'condition:Continue on the Yes branch when':'What needs to be true?',
  'delay:Wait for':'How long should I wait?',
  'delay:Unit':'Time unit',
  'stop:Final status':'How should the flow end?',
  'email:To':'Who should receive the email?',
  'email:Subject':'What should the subject say?',
  'email:Email body':'What should the email say?',
  'email:Importance':'Email priority',
  'getEmail:Message ID':'Which email should I open?',
  'getEmail:Include attachment content':'Also load its attachments?',
  'listEmail:Folder':'Which mail folder?',
  'listEmail:Search query':'What emails should I look for?',
  'listEmail:Maximum messages':'How many emails at most?',
  'listEmail:Unread only':'Unread emails only?',
  'attachment:Parent message ID':'Which email is it attached to?',
  'attachment:Attachment ID':'Which attachment should I open?',
  'htmlText:HTML content':'Which email or formatted text should I clean up?',
  'teams:Recipient work email':'Who should get the Teams message?',
  'teams:Message':'What should the message say?',
  'saveFile:Folder':'Which OneDrive folder?',
  'saveFile:Filename':'What should the file be called?',
  'saveFile:Content':'What should go in the file?',
  'readFile:File path':'Which file should I open?',
  'readFile:Infer content type':'Figure out the file type automatically?',
  'sharepoint:Site URL':'Which SharePoint site?',
  'sharepoint:List ID':'Which list?',
  'sharepoint:OData filter':'Only include items matching this filter',
  'sharepoint:Maximum records':'How many items at most?',
  'ai:Saved prompt ID':'Which saved AI prompt should I use?',
  'manual:Optional input schema':'Button inputs',
  'mail:Subject contains':'Only emails whose subject contains',
  'mail:Sender filter':'Only emails from',
  'mail:Folder':'Which mail folder?',
  'mail:Only emails with attachments':'Only emails with attachments?',
  'mail:Include attachment bytes':'Load the actual attachment files?',
  'schedule:Frequency':'How often?',
  'schedule:Every':'Repeat every',
  'schedule:Time zone':'Time zone',
  'request:Request JSON schema':'Information the other app will send'
 };
 return map[kind+':'+label]||label;
}
function fieldHint(kind,field){
 const key=kind+':'+field.label;
 const map={
  'email:To':'Enter one email address, or separate several addresses with semicolons.',
  'ai:Saved prompt ID':'Paste the ID of an AI prompt that already exists in Power Automate. If you do not know it, the easiest method is to open a working flow that already uses that prompt.',
  'loop:Repeat for each item in':'Usually you can click Insert value and choose a list made by an earlier step.',
  'filter:List':'Usually you can click Insert value and choose a list made by an earlier step.',
  'table:List of records':'Usually you can click Insert value and choose a list made by an earlier step.',
  'mail:Subject contains':'Leave this blank if every new email should start the flow.'
 };
 return map[key]||field.hint||'';
}
function beginAdd(scope,after=null){insertion={scope,after};tab='steps';query='';$('librarySearch').value='';renderLibrary();$('librarySearch').focus();if(innerWidth<=600)$('libraryList').scrollLeft=0;}
function addStep(k){let scope=insertion?.scope||['actions'],after=insertion?.after||null;if(!insertion){const cur=getSelected();if(cur&&!cur.trigger){if(C.branches(cur.a).length)scope=[...cur.path,'actions'];else{scope=cur.scope;after=cur.name;}}}if(k==='initialize'&&scope.length>1){scope=['actions'];after=null;notify('Saved information was added near the start so later steps can use it.');}mutate(()=>{selected=C.add(project,k,scope,after);insertion=null;});$('inspector').classList.add('open');}
function addPattern(kind){mutate(()=>{if(kind==='collect'){let vname='Results',i=2;const vs=C.walk(project.definition).flatMap(r=>r.a.inputs?.variables||[]).map(v=>v.name);while(vs.includes(vname))vname='Results'+i++;const init=C.add(project,'initialize');C.locate(project,init).a.inputs.variables=[{name:vname,type:'array',value:[]}];const loop=C.add(project,'loop');const comp=C.add(project,'compose',['actions',loop,'actions'],null,'Prepare one result');C.locate(project,comp).a.inputs=`@items('${loop}')`;const app=C.add(project,'appendArray',['actions',loop,'actions']);C.locate(project,app).a.inputs={name:vname,value:`@outputs('${comp}')`};selected=loop;}else{const work=C.add(project,'scope',['actions'],null,'Work to protect');const catchName=C.add(project,'scope',['actions'],null,'If the group fails');C.locate(project,catchName).a.runAfter={[work]:['Failed','TimedOut']};const mail=C.add(project,'email',['actions',catchName,'actions'],null,'Send failure alert');C.locate(project,mail).a.inputs.parameters['emailMessage/Body']='<p>The work group failed. Open the failed run in Power Automate to see the error.</p>';selected=work;}insertion=null;});$('inspector').classList.add('open');}
function loadRecipe(id){if(dirty&&!confirm('Replace the current canvas? Save your project first to keep a separate copy. Undo will also restore it in this session.'))return;mutate(()=>{project=C.recipe(id);selected=C.walk(project.definition).find(r=>C.kind(r.a)==='email')?.name||'$trigger';insertion=null;});notify('Template loaded. Click any box to change it.');}
function renderLibrary(){const isRecipes=tab==='recipes';$('recipesTab').classList.toggle('active',isRecipes);$('stepsTab').classList.toggle('active',!isRecipes);$('recipesTab').setAttribute('aria-pressed',isRecipes);$('stepsTab').setAttribute('aria-pressed',!isRecipes);$('librarySearch').placeholder=isRecipes?'What do you want to do?':'What should happen next?';$('catalogCount').textContent='';const list=$('libraryList');list.replaceChildren();
 if(!isRecipes&&insertion){const div=document.createElement('div');div.className='insertion';const inside=insertion.scope.length===1?'the main flow':nodeTitle(insertion.scope.filter(x=>!['actions','else','cases','default'].includes(x)).at(-1),C.locate(project,insertion.scope.filter(x=>!['actions','else','cases','default'].includes(x)).at(-1))?.a);div.textContent='New step will go inside '+inside+'.';list.append(div);}
 if(isRecipes){const matches=C.recipes.filter(r=>{const [t,d]=recipeCopy(r);return (t+' '+d).toLowerCase().includes(query);}),featured=new Set(['hello','summary','attachments','digest','blank']),shown=query||showAllTemplates?matches:matches.filter(r=>featured.has(r.id));for(const r of shown){const [t,d]=recipeCopy(r),b=document.createElement('button');b.className='recipe-card';b.innerHTML=`<strong>${esc(t)}</strong><small>${esc(d)}</small>`;b.onclick=()=>loadRecipe(r.id);list.append(b);}if(!query&&!showAllTemplates&&matches.length>shown.length){const more=document.createElement('button');more.className='more-templates';more.textContent='Show '+(matches.length-shown.length)+' more ideas';more.onclick=()=>{showAllTemplates=true;renderLibrary();};list.append(more);}}
 else{const all=Object.values(C.catalog).filter(c=>{const [t,d]=stepCopy(c);return (t+' '+d+' '+groupCopy(c.group)).toLowerCase().includes(query);}),shown=query||showAllSteps?all:all.filter(c=>COMMON_STEPS.has(c.id));if(showAllSteps&&!query){const h=document.createElement('div');h.className='groupname';h.textContent='Ready-made building blocks';list.append(h);for(const [id,label,desc] of [['collect','Go through a list and save the answers','Adds the repeating steps and a results list for you.'],['catch','Tell me if a group of steps fails','Adds a protected group and an email alert if something goes wrong.']]){const b=document.createElement('button');b.className='step-add';b.innerHTML=`<span class="mark">+</span><span><strong>${label}</strong><small>${desc}</small></span>`;b.onclick=()=>addPattern(id);list.append(b);}}let group='';for(const c of shown){const g=groupCopy(c.group),[t,d]=stepCopy(c);if(g!==group){group=g;const h=document.createElement('div');h.className='groupname';h.textContent=group;list.append(h);}const b=document.createElement('button');b.className='step-add';b.innerHTML=`<span class="mark">${esc(c.mark)}</span><span><strong>${esc(t)}</strong><small>${esc(d)}</small></span>`;b.onclick=()=>addStep(c.id);list.append(b);}if(!query&&!showAllSteps&&all.length>shown.length){const more=document.createElement('button');more.className='more-templates';more.textContent='Show more step types';more.onclick=()=>{showAllSteps=true;renderLibrary();};list.append(more);}}
 if(!list.children.length){const n=document.createElement('p');n.className='empty-result';n.textContent='Nothing matched. Try a different word.';list.append(n);}
}
function description(a){const k=C.kind(a),pp=a.inputs?.parameters||{};if(k==='email')return pp['emailMessage/To']?'Send to '+pp['emailMessage/To']:'Choose who should receive it';if(k==='loop')return 'Repeat '+Object.keys(a.actions||{}).length+' step'+(Object.keys(a.actions||{}).length===1?'':'s')+' for each item';if(k==='ai')return pp.recordId?'Use your saved AI prompt':'Choose a saved AI prompt';if(k==='initialize')return 'Remember something called '+(a.inputs.variables[0]?.name||'this value');if(k==='condition')return 'If yes, do one thing. If no, do another.';if(k==='scope')return 'Keep '+Object.keys(a.actions||{}).length+' step'+(Object.keys(a.actions||{}).length===1?'':'s')+' together';if(k==='compose')return 'Keep this information for the next steps';return stepCopy(C.catalog[k]||{id:'unknown',title:'Imported step',description:'Imported from an existing flow.'})[1];}
function renderTree(){const issues=C.validate(project),tree=$('flowTree');tree.replaceChildren();const tn=Object.keys(project.definition.triggers)[0],ta=project.definition.triggers[tn],tk=C.triggerKind(ta),[tt]=triggerCopy(tk);const wrap=document.createElement('div');wrap.className='node-wrap';const b=document.createElement('button');b.className='node'+(selected==='$trigger'?' selected':'');let sub='Choose when this automation should start';if(tk==='mail')sub=ta.inputs.parameters.subjectFilter?'Only emails with subject containing: '+ta.inputs.parameters.subjectFilter:'Any new email';if(tk==='schedule')sub='Runs automatically on your schedule';if(tk==='manual')sub='You start it yourself';b.innerHTML=`<span class="mark ${tk==='mail'?'outlook':''}">ϟ</span><span class="node-main"><strong>${esc(tt)}</strong><small>${esc(sub)}</small></span><span class="nodetag">WHEN</span>`;b.onclick=()=>select('$trigger');wrap.append(b);tree.append(wrap);
 function nodes(acts,host,path){for(const [name,a] of Object.entries(acts)){const c=C.catalog[C.kind(a)],problems=issues.filter(x=>x.node===name),err=problems.filter(x=>x.severity==='error').length,outer=document.createElement('div');outer.className='node-wrap';const button=document.createElement('button');button.className='node'+(selected===name?' selected':'');button.dataset.node=name;button.innerHTML=`<span class="mark ${(c?.group||'advanced').toLowerCase().replace(/\s+/g,'')}">${esc(c?.mark||'{ }')}</span><span class="node-main"><strong>${esc(nodeTitle(name,a))}</strong><small>${esc(description(a))}</small></span>${err?`<span class="nodetag error">${err} TO FIX</span>`:!c?'<span class="nodetag warn">IMPORTED</span>':'<span class="subtle" aria-hidden="true">›</span>'}`;button.onclick=()=>select(name);outer.append(button);
  for(const [branchPath,label] of C.branches(a)){const br=document.createElement('div');br.className='branch';const head=document.createElement('div');head.className='branch-head';const l=document.createElement('span');l.textContent=branchCopy(label);const add=document.createElement('button');add.textContent='+';add.title='Add something here';add.setAttribute('aria-label',add.title);const scope=[...path,name,...branchPath];add.onclick=()=>beginAdd(scope);head.append(l,add);br.append(head);const children=C.get(a,branchPath);nodes(children,br,scope);if(!Object.keys(children).length){const empty=document.createElement('button');empty.className='branch-empty';empty.textContent='+ Add something here';empty.onclick=()=>beginAdd(scope);br.append(empty);}outer.append(br);}host.append(outer);}}
 nodes(project.definition.actions,tree,['actions']);const intro=$('flowIntro');intro.innerHTML=`<span class="intro-icon">2</span><div><strong>${project.imported?'Your imported automation is ready to edit':'Your automation runs from top to bottom'}</strong><p>${project.imported?'Click any box to change it. Flowcraft keeps settings it does not understand instead of deleting them.':'Click a box to fill in the blanks. Add another box whenever you need the automation to do something else.'}</p></div>`;$('undoBtn').disabled=!history.length;$('redoBtn').disabled=!future.length;
}
function issues(){const result=C.validate(project);for(const key of pending)result.unshift({severity:'error',node:selected==='$trigger'?null:selected,text:'An edited field has invalid JSON or an invalid value. Fix or discard that field before export.'});return result;}
function renderChecks(){const all=issues(),errors=all.filter(x=>x.severity==='error').length,warnings=all.length-errors;const b=$('checkBar');b.innerHTML=`<span class="checksummary"><span class="dot ${errors?'error':warnings?'warn':''}"></span><span>${errors?errors+' '+(errors===1?'thing needs':'things need')+' your attention':warnings?'Looks ready, with '+warnings+' note'+(warnings===1?'':'s'):'Looks ready to download'}</span></span><span class="between"><button id="reviewChecks">${errors?'Show me what to fix':'Check details'}</button></span>`;$('reviewChecks').onclick=()=>showExport(false);const panel=$('inspectorIssues');if(panel){panel.replaceChildren();for(const issue of all.filter(x=>selected==='$trigger'?!x.node:x.node===selected).slice(0,6)){const el=document.createElement('div');el.className='notice'+(issue.severity==='error'?' red':'');el.textContent=issue.text;panel.append(el);}}}
function modal(titleText,kicker,content){modalReturnFocus=document.activeElement;$('modalTitle').textContent=titleText;$('modalKicker').textContent=kicker;$('modalBody').replaceChildren();if(typeof content==='string')$('modalBody').innerHTML=content;else $('modalBody').append(content);if(!$('modal').open)$('modal').showModal();}
function closeModal(){$('modal').close();referenceTarget=null;if(modalReturnFocus?.isConnected)modalReturnFocus.focus();}
function currentField(field){return C.get(getSelected()?.a,field.path);}
function changeField(field,value,full=false){const s=getSelected();if(!s)return;mutate(()=>C.put(s.a,field.path,value),full);}
function fieldLabel(field){return field.label;}
function bindingLabel(value){const r=C.refs(project,selected).find(r=>r.value===value);return r?r.group+' → '+r.label:'Custom expression';}
function mountField(host,field,a,customChange=null){const v=C.get(a,field.path),id='field_'+Math.random().toString(36).slice(2),key=JSON.stringify(field.path);const block=document.createElement('div');block.className='field';const head=document.createElement('div');head.className='fieldhead';const lab=document.createElement('label');lab.className='fieldlabel';lab.htmlFor=id;const fk=getSelected()?.trigger?C.triggerKind(getSelected().a):C.kind(getSelected()?.a);const friendlyLabel=fieldCopy(fk,field.label);lab.innerHTML=esc(friendlyLabel)+(field.required?' <span class="req">*</span>':'');head.append(lab);block.append(head);const assign=value=>{pending.delete(key);if(customChange)customChange(value);else changeField(field,value);};
 if(field.type==='boolean'){const label=document.createElement('label');label.className='between';const input=document.createElement('input');input.type='checkbox';input.id=id;input.checked=!!v;const text=document.createElement('span');text.className='smallnote';text.textContent='Enabled';input.onchange=()=>assign(input.checked);label.append(text,input);block.append(label);}
 else if(['select','variable'].includes(field.type)){const sel=document.createElement('select');sel.id=id;let opts=field.options||C.walk(project.definition).flatMap(r=>r.a.type==='InitializeVariable'?(r.a.inputs.variables||[]).map(x=>x.name):[]);if(!opts.includes(v)&&v!==undefined&&v!=='')opts=[v,...opts];if(field.type==='variable')opts=['',...opts];for(const op of [...new Set(opts)]){const o=new Option(op||'Choose a variable',op);sel.add(o);}sel.value=v??'';sel.onchange=()=>{assign(sel.value);if(field.path.at(-1)==='frequency'&&['Minute','Hour'].includes(sel.value)){mutate(()=>delete a.recurrence.schedule);}else if(field.path.at(-1)==='type'&&getSelected()?.a.type==='InitializeVariable'){notify('Also check that the starting value matches the new type.');renderInspector();}};block.append(sel);}
 else if(field.type==='condition'){const inp=document.createElement('textarea');inp.id=id;inp.className='code';inp.value=typeof v==='string'?v:C.j(v);inp.rows=3;const helper=document.createElement('button');helper.type='button';helper.textContent=advanced?'Build condition':'Set the rule';helper.className='pillbtn';head.append(helper);helper.onclick=()=>conditionDialog(field,typeof v==='string');inp.onchange=()=>{try{const x=inp.value.trim();const value=x.startsWith('@')?x:JSON.parse(x);assign(value);inp.classList.remove('invalid');}catch{pending.add(key);dirty=true;inp.classList.add('invalid');renderChecks();notify('Use a condition expression or valid JSON.');}};block.append(inp);}
 else{let mode=field.type==='json'?'json':field.type==='number'?'number':typeof v==='string'?'text':'json';if(field.type==='value'){const modes=document.createElement('div');modes.className='mode';const selectMode=document.createElement('select');selectMode.setAttribute('aria-label',field.label+' value type');for(const [x,l] of [['text','Text'],['json','List / structured information']])selectMode.add(new Option(l,x));selectMode.value=mode;modes.append(selectMode);block.append(modes);selectMode.onchange=()=>{mode=selectMode.value;input.value=mode==='json'?(typeof currentField(field)==='string'?JSON.stringify(currentField(field)):C.j(currentField(field))):(typeof currentField(field)==='string'?currentField(field):String(currentField(field)??''));input.hidden=false;binding?.remove();};}
 const input=document.createElement(field.type==='textarea'||field.type==='json'||field.type==='value'?'textarea':'input');input.id=id;input.dataset.path=key;input.autocomplete='off';input.spellcheck=false;input.value=v===undefined?'':typeof v==='string'?v:C.j(v);if(field.type==='number'){input.type='number';input.step='1';}if(mode==='json')input.classList.add('code');const err=document.createElement('div');err.className='field-error';
 const apply=()=>{try{let value=input.value;if(mode==='json')value=field.type==='value'&&input.value.startsWith('@')?input.value:JSON.parse(input.value);if(mode==='number'){if(!input.value.trim()&&!field.required){const s=getSelected();mutate(()=>{const holder=C.get(s.a,field.path.slice(0,-1));delete holder[field.path.at(-1)];},false);pending.delete(key);return;}value=Number(input.value);if(!Number.isFinite(value))throw Error('Enter a number.');}assign(value);input.classList.remove('invalid');err.textContent='';}catch(e){pending.add(key);dirty=true;input.classList.add('invalid');err.textContent=mode==='json'?'Not valid JSON. This edit has not been applied.':e.message;renderChecks();}};input.onchange=apply;
 let binding=null;const expression=typeof v==='string'&&v.startsWith('@')&&!v.startsWith('@@');if(expression&&!advanced&&field.type!=='json'){binding=document.createElement('div');binding.className='binding';const text=document.createElement('span');text.textContent=bindingLabel(v);const choose=document.createElement('button');choose.type='button';choose.textContent='Change';choose.onclick=()=>referenceDialog(field,input,apply);const raw=document.createElement('button');raw.type='button';raw.textContent='Edit';raw.onclick=()=>{input.hidden=false;binding.remove();input.focus();};binding.innerHTML='<span class="binding-icon">↳</span>';binding.append(text,choose,raw);block.append(binding);input.hidden=true;}
 if(!['json','number'].includes(field.type)&&field.label!=='Step name'){const insert=document.createElement('button');insert.className='link';insert.type='button';insert.textContent='Use an earlier answer';insert.onclick=()=>referenceDialog(field,input,()=>{apply();renderInspector();});head.append(insert);}block.append(input,err);
 if(field.type==='json'&&field.path.at(-1)==='schema'){const gen=document.createElement('button');gen.className='pillbtn';gen.textContent='Generate schema from example';gen.onclick=()=>schemaDialog(field);block.append(gen);}
 }
 const friendlyHint=fieldHint(fk,field);if(friendlyHint){const help=document.createElement('div');help.className='help';help.textContent=friendlyHint;block.append(help);}host.append(block);return block;
}
function renderInspector(){const host=$('inspector'),s=getSelected();host.replaceChildren();if(!s){host.innerHTML='<div class="emptyinspector"><h2>Choose a box</h2><p>Click any box in the middle. The questions for that box will appear here.</p></div>';return;}const k=s.trigger?C.triggerKind(s.a):C.kind(s.a),c=s.trigger?C.triggers[k]:C.catalog[k],head=document.createElement('div');head.className='inspector-head';const [plainHead,plainDesc]=s.trigger?triggerCopy(k):stepCopy(c||{id:'unknown',title:'Imported step',description:'This came from an imported flow.'});head.innerHTML=`<div class="inspector-head-top"><span class="eyebrow">${s.trigger?'WHEN THIS HAPPENS':'THEN DO THIS'}</span><button class="mobile-back pillbtn" id="backToFlow">Back to flow</button></div><h2>${esc(plainHead)}</h2><p>${esc(plainDesc)}</p>`;host.append(head);$('backToFlow').onclick=()=>host.classList.remove('open');const body=document.createElement('div');body.className='inspector-body';host.append(body);
 if(s.trigger){const label=document.createElement('div');label.className='field';label.innerHTML='<div class="fieldhead"><label class="fieldlabel" for="triggerPicker">What should start this automation?</label></div>';const picker=document.createElement('select');picker.id='triggerPicker';for(const [key,tr] of Object.entries(C.triggers))picker.add(new Option(tr.title,key));if(k==='unknown')picker.add(new Option('Preserved custom trigger','unknown'));picker.value=k;picker.onchange=()=>{if(confirm('Change the trigger? Existing steps are preserved, but their references may need adjusting.'))mutate(()=>C.switchTrigger(project,picker.value));else picker.value=k;};label.append(picker);body.append(label);}
 else if(advanced){const field=C.clone(C.catalog.compose.fields[0]);field.label='Box name';field.type='text';field.required=false;field.hint='Optional. Give this box a name that makes sense to you.';field.path=['label'];mountField(body,field,{label:title(s.name)},value=>mutate(()=>project.labels[s.name]=value,false));}
 if(c?.note&&advanced){const note=document.createElement('div');note.className='notice';note.textContent=c.note;body.append(note);}for(const field of c?.fields||[]){if(s.trigger&&k==='schedule'&&!advanced&&field.path.at(-1)==='schedule')continue;if(k==='loop'&&!advanced&&field.path.at(-1)==='repetitions')continue;mountField(body,field,s.a);}if(s.trigger&&k==='schedule'&&!advanced&&['Day','Week'].includes(s.a.recurrence.frequency)){const rec=s.a.recurrence,details=rec.schedule||{};if((details.hours?.length||0)>1||(details.minutes?.length||0)>1){const n=document.createElement('div');n.className='notice';n.textContent='Multiple scheduled times are preserved. Use Advanced settings to edit this schedule.';body.append(n);}else{const n=document.createElement('div');n.className='field';n.innerHTML='<label class="fieldlabel" for="scheduleAt">At this local time</label>';const t=document.createElement('input');t.type='time';t.id='scheduleAt';t.className='space';t.value=String(details.hours?.[0]??8).padStart(2,'0')+':'+String(details.minutes?.[0]??0).padStart(2,'0');t.onchange=()=>{if(!t.value)return;const [h,m]=t.value.split(':').map(Number);mutate(()=>{rec.schedule??={};rec.schedule.hours=[h];rec.schedule.minutes=[m];},false);};n.append(t);body.append(n);}if(rec.frequency==='Week'){const n=document.createElement('div');n.className='field';n.innerHTML='<p class="fieldlabel">On these days</p>';for(const day of ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']){const l=document.createElement('label');l.className='between form-line smallnote';l.textContent=day;const ch=document.createElement('input');ch.type='checkbox';ch.checked=(details.weekDays||[]).includes(day);ch.onchange=()=>mutate(()=>{rec.schedule??={};const days=new Set(rec.schedule.weekDays||[]);ch.checked?days.add(day):days.delete(day);rec.schedule.weekDays=[...days];},false);l.append(ch);n.append(l);}body.append(n);}}
 if(k==='ai'){const pp=s.a.inputs.parameters,group=document.createElement('div');group.className='promptmap';group.innerHTML='<div class="between"><strong>What should AI receive?</strong><button id="addPromptInput" class="pillbtn">+ Add AI input</button></div><p class="smallnote space">These names must match the inputs in your saved AI prompt. If you copied this step from a working flow, they are usually already filled in.</p>';body.append(group);for(const key of Object.keys(pp).filter(x=>x.startsWith('item/requestv2/'))){const field={label:key.slice(15),path:['inputs','parameters',key],type:'value',required:true};mountField(group,field,s.a);const rm=document.createElement('button');rm.className='link';rm.textContent='Remove '+field.label;rm.onclick=()=>mutate(()=>delete pp[key]);group.append(rm);}$('addPromptInput').onclick=()=>{const key=prompt('Exact text-input name from the saved prompt (for example EmailBody):');if(key?.trim()){const clean=key.trim();if(!/^[a-zA-Z0-9_ /-]+$/.test(clean)){notify('Use the exact connector input name, without braces or quotes.');return;}mutate(()=>pp['item/requestv2/'+clean]='');}};}
 if(k==='email'){const preview=document.createElement('button');preview.className='quiet';preview.textContent='Preview the email';preview.onclick=emailPreview;body.append(preview);}const t=document.createElement('div');t.className='toggle-row';t.innerHTML=`<label><input type="checkbox" id="advancedToggle" ${advanced?'checked':''}> Need more options?</label><span>Technical</span>`;body.append(t);$('advancedToggle').onchange=()=>{advanced=$('advancedToggle').checked;renderInspector();};
 if(advanced){const code=document.createElement('div');code.className='smallnote';code.textContent='Internal name: '+s.name;body.append(code);if(!s.trigger){const acts=C.get(project.definition,s.scope),keys=Object.keys(acts),prev=keys[keys.indexOf(s.name)-1];const row=document.createElement('div');row.className='field space';row.innerHTML='<label class="fieldlabel" for="runWhen">Run after the previous step</label>';const sel=document.createElement('select');sel.id='runWhen';sel.className='space';for(const [v,l] of [['success','Succeeds'],['failure','Fails or times out'],['always','Finishes in any state'],['custom','Custom dependencies (preserved)']])sel.add(new Option(l,v));const ra=s.a.runAfter||{},flags=prev?ra[prev]:null;sel.value=!prev&&!Object.keys(ra).length?'success':Object.keys(ra).length===1&&flags?C.j(flags)===C.j(['Succeeded'])?'success':C.j(flags)===C.j(['Failed','TimedOut'])?'failure':C.j(flags)===C.j(['Succeeded','Failed','Skipped','TimedOut'])?'always':'custom':'custom';sel.disabled=!prev;sel.onchange=()=>{if(sel.value==='custom')return;mutate(()=>s.a.runAfter={[prev]:sel.value==='success'?['Succeeded']:sel.value==='failure'?['Failed','TimedOut']:['Succeeded','Failed','Skipped','TimedOut']});};row.append(sel);body.append(row);}
 const raw=document.createElement('button');raw.className='quiet space';raw.textContent='Edit this step as JSON';raw.onclick=()=>rawDialog();body.append(raw);const expl=document.createElement('p');expl.className='smallnote space';expl.textContent='Raw edits preserve unsupported properties. Local checks are not Microsoft’s save/import validator.';body.append(expl);}
 if(k==='unknown'&&!advanced){const raw=document.createElement('button');raw.textContent='Open preserved JSON';raw.onclick=rawDialog;body.append(raw);}
 if(!s.trigger){const actions=document.createElement('div');actions.className='inspector-actions';for(const [label,fn] of [['↑',()=>mutate(()=>C.move(project,s.name,-1))],['↓',()=>mutate(()=>C.move(project,s.name,1))],['Duplicate',()=>mutate(()=>selected=C.duplicate(project,s.name))],['Delete',()=>{if(confirm('Delete this step and everything inside it? References elsewhere will be flagged. You can undo this.'))mutate(()=>{C.remove(project,s.name);selected=null;});}]]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',label==='↑'?'Move step up':label==='↓'?'Move step down':label);if(label==='Delete')b.className='danger';b.onclick=fn;actions.append(b);}body.append(actions);const add=document.createElement('button');add.textContent=C.branches(s.a).length?'+ Add inside this group':'+ Add after this step';add.className='quiet';add.style.width='100%';add.onclick=()=>beginAdd(C.branches(s.a).length?[...s.path,'actions']:s.scope,C.branches(s.a).length?null:s.name);body.append(add);}
 const current=issues().filter(x=>s.trigger?!x.node:x.node===s.name);{const note=document.createElement('div');note.id='inspectorIssues';note.className='space';for(const issue of current.slice(0,6)){const div=document.createElement('div');div.className='notice'+(issue.severity==='error'?' red':'');div.textContent=issue.text;note.append(div);}body.append(note);}
}
function emailPreview(){const a=getSelected()?.a;if(!a)return;let html=a.inputs.parameters['emailMessage/Body']||'';const match=typeof html==='string'&&html.match(/^@outputs\('([^']+)'\)$/);if(match){const src=C.locate(project,match[1])?.a;if(src?.type==='Compose'&&typeof src.inputs==='string'&&!src.inputs.startsWith('@'))html=src.inputs;else html='<p>[Dynamic body: available only when the flow runs]</p>';}else if(typeof html!=='string'||html.startsWith('@'))html='<p>[Dynamic body: available only when the flow runs]</p>';modal('Email layout preview','STATIC PREVIEW · NOT A TEST RUN','<p>Only literal HTML and direct literal Compose values are previewed. Dynamic results are not evaluated. Scripts, forms, and remote images are blocked.</p><iframe id="emailPreview" class="previewframe" sandbox="" title="Sandboxed email layout preview"></iframe>');$('emailPreview').srcdoc='<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src \'none\'; form-action \'none\'"><style>body{font:14px/1.7 system-ui;color:#26372d;padding:18px;overflow-wrap:anywhere}</style>'+html;}
function referenceDialog(field,input,apply){referenceTarget={field,input,apply};const refs=C.refs(project,selected);modal('Use a value from your flow','NO EXPRESSION TYPING REQUIRED','<div class="refsearch"><input id="refSearch" placeholder="Find a field or step…" aria-label="Search available values"></div><div id="refList"></div><p class="smallnote space">Only earlier steps on the dependency path are offered. Choosing a value inserts the actual Power Automate expression. Nothing is fetched or evaluated here.</p>');const build=q=>{const list=$('refList');list.replaceChildren();let group='';for(const r of refs.filter(r=>(r.group+' '+r.label).toLowerCase().includes(q.toLowerCase()))){if(group!==r.group){group=r.group;const h=document.createElement('div');h.className='refgroup';h.textContent=group;list.append(h);}const b=document.createElement('button');b.className='refoption';b.innerHTML=`<strong>${esc(r.label)}</strong>${advanced?'<small>'+esc(r.value)+'</small>':''}`;b.onclick=()=>{const target=referenceTarget;if(!target)return;let value=r.value;if(target.input.value&&!target.input.value.startsWith('@')&&target.field.type==='textarea'){const start=target.input.selectionStart??target.input.value.length,end=target.input.selectionEnd??start;value=target.input.value.slice(0,start)+'@{'+value.slice(1)+'}'+target.input.value.slice(end);}target.input.value=value;closeModal();target.apply();renderInspector();};list.append(b);}if(!list.children.length){const p=document.createElement('p');p.textContent='No matching values are available here.';list.append(p);}};build('');$('refSearch').oninput=()=>build($('refSearch').value);$('refSearch').focus();}
function conditionDialog(field,stringResult){
 modal('Build a condition','TWO VALUES, ONE DECISION','<p>Choose a value from earlier in the flow or type a literal value. These controls build the expression for you.</p><div id="condFields"></div><button class="primary" id="applyCondition">Use this condition</button>');
 const area=$('condFields'),refs=C.refs(project,selected),values={left:'',right:''};
 for(const side of ['left','right']){const wrap=document.createElement('div');wrap.className='field';const lab=document.createElement('label');lab.className='fieldlabel';lab.textContent=side==='left'?'Left value':'Right value';const sel=document.createElement('select');sel.className='space';sel.setAttribute('aria-label',lab.textContent+' source');sel.add(new Option('Type a value',''));refs.forEach(r=>sel.add(new Option(r.group+' → '+r.label,r.value)));const text=document.createElement('input');text.setAttribute('aria-label',lab.textContent);text.className='space';text.oninput=()=>values[side]=text.value;sel.onchange=()=>{text.hidden=!!sel.value;values[side]=sel.value||text.value;};wrap.append(lab,sel,text);area.append(wrap);if(side==='left'){const op=document.createElement('select');op.id='conditionOperator';op.setAttribute('aria-label','Comparison');for(const [v,l] of [['equals','is equal to'],['contains','contains'],['greater','is greater than'],['less','is less than'],['greaterOrEquals','is at least'],['lessOrEquals','is at most']])op.add(new Option(l,v));area.append(op);}}
 const type=document.createElement('select');type.id='rightType';type.setAttribute('aria-label','Right value type');for(const v of ['text','number','boolean'])type.add(new Option('Treat typed right value as '+v,v));area.append(type);
 $('applyCondition').onclick=()=>{let right=values.right;if(!right.startsWith('@')){if(type.value==='number'){right=Number(right);if(!values.right.trim()||!Number.isFinite(right)){notify('Enter a valid number.');return;}}if(type.value==='boolean'){if(!['true','false'].includes(right)){notify('Use true or false.');return;}right=right==='true';}}let result={[$('conditionOperator').value]:[values.left,right]};if(stringResult){const literal=v=>typeof v==='string'?v.startsWith('@')?v.slice(1):"'"+v.replace(/'/g,"''")+"'":String(v);result='@'+$('conditionOperator').value+'('+literal(values.left)+', '+literal(right)+')';}changeField(field,result,true);closeModal();};
}
function schemaDialog(field){modal('Generate a JSON schema','FROM A REPRESENTATIVE EXAMPLE','<p>Paste a small example of the data you expect. This generator uses the first array item and does not infer every possible variation or required field.</p><textarea id="schemaSample" rows="10" class="code" placeholder=\'{"name":"Example","items":[{"title":"Review"}]}\' aria-label="Sample JSON"></textarea><button id="generateSchema" class="primary space">Use generated schema</button>');$('generateSchema').onclick=()=>{try{const schema=C.schemaFrom(JSON.parse($('schemaSample').value));changeField(field,schema,true);closeModal();}catch(e){notify('That example is not valid JSON: '+e.message);}};}
function rawDialog(){const s=getSelected();if(!s)return;modal('Edit preserved JSON','ADVANCED · THIS ACTION ONLY','<p>Only this action is replaced. Names, metadata, retry settings, unknown properties, and nested actions are kept unless you remove them here. Use Undo to recover a prior version.</p><textarea id="rawEditor" rows="17" class="code" aria-label="Raw step JSON"></textarea><button id="applyRaw" class="primary space">Apply JSON</button>');$('rawEditor').value=C.j(s.a);$('applyRaw').onclick=()=>{try{const data=JSON.parse($('rawEditor').value);if(!C.object(data)||typeof data.type!=='string')throw Error('The action needs a type property.');mutate(()=>{if(s.trigger)project.definition.triggers[s.name]=data;else C.put(project.definition,s.path,data);C.register(project,data);for(const r of C.walk({actions:{Root:data}}))C.register(project,r.a);});closeModal();}catch(e){notify(e.message);}};}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const filename=()=>project.name.replace(/[^a-z0-9._-]+/gi,'_').slice(0,90)||'My_flow';
function saveProject(){if(pending.size){notify('Fix the invalid field before saving, or select another step to discard that edit.');return;}download(filename()+'.flowcraft.json',C.j(project),'application/json');dirty=false;persist();notify('Project file saved. Open it here later to keep editing.');}
function showExport(wantExport=true){const all=issues(),errors=all.filter(x=>x.severity==='error'),notes=all.filter(x=>x.severity==='warning');const connections=Object.entries(C.usedConnections(project));modal(wantExport?'Download your Power Automate file':'Check before downloading','LAST STEP',`<div class="exportcards"><div class="exportcard"><strong>${errors.length?errors.length+' '+(errors.length===1?'thing needs':'things need')+' fixing':'Everything Flowcraft can check looks good'}</strong><p>${errors.length?'Click a problem below to go straight to it.':'Microsoft will do its own final checks when you import the file.'}</p></div><div class="exportcard"><strong>${connections.length?connections.length+' Microsoft connection'+(connections.length===1?'':'s')+' needed':'No Microsoft connections needed'}</strong><p>${connections.length?'During import, Power Automate will ask you to choose your Outlook, Teams, OneDrive, or other accounts as needed.':'This flow does not use a connected Microsoft service.'}</p></div></div><div id="exportIssues" class="space"></div><div id="exportConnections"></div><details><summary>Technical notes (${notes.length})</summary><div id="exportNotes" class="checkdetails"></div></details><div class="notice green"><strong>After downloading:</strong> In Power Automate, go to <strong>My flows → Import → Import Package (Legacy)</strong>. Choose <strong>Create as new</strong>, pick the requested connections, import it, and test the new flow before relying on it.</div><div class="between"><button id="downloadZip" class="primary" ${errors.length?'disabled':''}>Download ZIP</button><button id="exportProject" class="quiet">Save an editable backup</button></div><p class="smallnote space">This ZIP contains the flow instructions. It does not include your passwords, Microsoft connections, or a new AI prompt.</p>`);
 const show=(container,list)=>{for(const x of list){const b=document.createElement('button');b.className='issue '+x.severity;b.innerHTML=`<strong>${esc(x.node?nodeTitle(x.node,C.locate(project,x.node)?.a):'Flow setup')}</strong><small>${esc(x.text)}</small>`;b.onclick=()=>{closeModal();select(x.node||'$trigger');};container.append(b);}};show($('exportIssues'),errors);show($('exportNotes'),notes);for(const [key,ref] of connections){const name=ref.id?.split('/').at(-1)||ref.api?.name||key;const div=document.createElement('div');div.className='connection';div.innerHTML=`${esc(C.connectors[name]||name)}<span>You choose this during import</span>`;$('exportConnections').append(div);}$('downloadZip').onclick=()=>{try{const files=C.packageFiles(project);download(filename()+'.zip',Z.store(files),'application/zip');notify('ZIP downloaded. Next, import it in Power Automate.');}catch(e){notify(e.message);}};$('exportProject').onclick=saveProject;}
function inspect(){modal('Under the hood','LIVE WORKFLOW DEFINITION','<p>This is the actual definition included in the exported ZIP. Advanced and unknown properties from imported flow packages are preserved. This preview never executes anything.</p><div class="between"><button id="copyJson">Copy JSON</button><button id="getDefinition">Download definition</button></div><pre id="jsonPreview" tabindex="0"></pre>');$('jsonPreview').textContent=C.j(project.definition);$('copyJson').onclick=async()=>{try{await navigator.clipboard.writeText(C.j(project.definition));notify('Definition copied.');}catch{const r=document.createRange();r.selectNodeContents($('jsonPreview'));getSelection().removeAllRanges();getSelection().addRange(r);notify('JSON selected. Use your browser’s Copy command.');}};$('getDefinition').onclick=()=>download(filename()+'.definition.json',C.j(project.definition),'application/json');}
function help(){modal('How this works','NO TECHNICAL KNOWLEDGE NEEDED',`<p><strong>1. Pick the closest idea.</strong> For example, “Summarize new emails with AI” or “Save email attachments.” You can change every part afterward.</p><p><strong>2. Read from top to bottom.</strong> The first box says <em>when</em> the automation starts. Every box underneath says what happens next. Click a box and answer the questions on the right.</p><p><strong>3. Connect answers when needed.</strong> If one step needs information from an earlier step, click <em>Use an earlier answer</em> and pick it from the list. You do not need to type Power Automate code.</p><p><strong>4. Download the ZIP.</strong> When the bottom bar says it looks ready, click <em>Download ZIP</em>. Then import that ZIP in Power Automate under <em>My flows → Import → Import Package (Legacy)</em>.</p><h3>What if I see something technical?</h3><p>You normally should not. Extra step types and technical settings are hidden until you ask for them. Imported flows may contain special steps Flowcraft preserves even when it cannot simplify them.</p><h3>AI prompts</h3><p>Flowcraft can use an AI prompt that already exists in your Microsoft environment. It does not create or package a brand-new AI prompt in this version.</p>`);}
function privacy(){modal('Your work stays here','LOCAL DATA & PRIVACY',`<p>This page has no backend, analytics, remote scripts, or Microsoft login. Opening a project or flow ZIP does not upload it. The ZIP is constructed in your browser.</p><label class="between"><span><strong>Remember my project in this browser</strong><br><span class="smallnote">Off by default. Includes all values you entered or imported.</span></span><input id="rememberToggle" type="checkbox" ${remember?'checked':''}></label><div class="notice space">Browser storage and exported files are not encrypted. Anyone using this browser profile, or other scripts on the same site, may be able to read saved data. Do not treat it as a vault for client records or credentials.</div><p>Saving a project file gives you a portable backup without browser storage. Clearing browser storage does not delete downloaded files.</p><button id="forgetProject" class="danger">Clear saved browser copy</button><p class="smallnote space">This removes only Flowcraft’s saved project and preference, not your current canvas or other Misc projects.</p>`);$('rememberToggle').onchange=()=>{remember=$('rememberToggle').checked;try{if(remember)localStorage.setItem(CONSENT,'yes');else{localStorage.removeItem(CONSENT);localStorage.removeItem(STORE);}persist();}catch{remember=false;$('rememberToggle').checked=false;notify('Browser storage is unavailable. Save a project file instead.');}};$('forgetProject').onclick=()=>{try{localStorage.removeItem(STORE);localStorage.removeItem(CONSENT);}catch{}remember=false;$('rememberToggle').checked=false;persist();notify('Saved browser copy cleared. Current canvas is unchanged.');};}
async function importFile(file){if(!file)return;if(file.size>25*1024*1024){notify('Import is limited to 25 MB.');return;}try{let p;if(file.name.toLowerCase().endsWith('.zip'))p=C.importLegacy(await Z.read(new Uint8Array(await file.arrayBuffer())));else p=C.assertProject(JSON.parse(await file.text()));if(dirty&&!confirm('Replace the current canvas with this file? Save a project copy first to keep it. Undo can also restore the canvas.'))return;mutate(()=>{project=C.clone(p);selected=C.walk(project.definition)[0]?.name||'$trigger';insertion=null;});notify('Opened locally. Original file is unchanged. Review notes before export.');}catch(e){notify('Not opened: '+e.message);}finally{$('openFile').value='';}}
function render(){pending.clear();$('projectName').value=project.name;renderLibrary();renderTree();renderInspector();renderChecks();}
$('projectName').onchange=()=>mutate(()=>project.name=$('projectName').value,false);
$('recipesTab').onclick=()=>{tab='recipes';query='';$('librarySearch').value='';renderLibrary();};$('stepsTab').onclick=()=>{tab='steps';query='';$('librarySearch').value='';renderLibrary();};$('librarySearch').oninput=()=>{query=$('librarySearch').value.trim().toLowerCase();renderLibrary();};
$('menuBtn').onclick=()=>{modal('More options','FLOWCRAFT','<div class="menu-stack"><button id="menuSave">Save editable project</button><button id="menuJson">View workflow JSON</button><button id="menuHelp">How it works</button><button id="menuPrivacy">Privacy</button></div>');$('menuSave').onclick=()=>{closeModal();saveProject();};$('menuJson').onclick=()=>{closeModal();inspect();};$('menuHelp').onclick=help;$('menuPrivacy').onclick=privacy;};$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('addRoot').onclick=()=>beginAdd(['actions']);$('exportBtn').onclick=()=>showExport();$('saveBtn').onclick=saveProject;$('inspectBtn').onclick=inspect;$('helpBtn').onclick=help;$('privacyBtn').onclick=privacy;$('openBtn').onclick=()=>$('openFile').click();$('openFile').onchange=()=>importFile($('openFile').files[0]);$('closeModal').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();document.activeElement?.blur();saveProject();}if((e.ctrlKey||e.metaKey)&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!$('modal').open&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}});
window.addEventListener('beforeunload',e=>{if(dirty&&!remember){e.preventDefault();e.returnValue='';}});
document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});document.addEventListener('drop',e=>{if(e.dataTransfer?.files.length){e.preventDefault();importFile(e.dataTransfer.files[0]);}});
// A tiny public testing surface: read-only snapshots, no evaluation or network calls.
window.Flowcraft={version:'1.2.0',snapshot:()=>C.clone(project),checks:()=>issues(),openFile:importFile};
render();persist();
})();

// Flowcraft 1.1 simplified UI
