/* Flowcraft core. Native workflow JSON is the source of truth, not a lossy diagram. */
(function (root) {
'use strict';
const clone = x => JSON.parse(JSON.stringify(x));
const own = (o,k) => Object.prototype.hasOwnProperty.call(o,k);
const object = x => !!x && typeof x === 'object' && !Array.isArray(x);
const uid = () => (globalThis.crypto?.randomUUID?.() || 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return (c==='x'?r:r&3|8).toString(16);}));
const j = x => JSON.stringify(x,null,2);
const API='/providers/Microsoft.PowerApps/apis/';
const connectors={shared_office365:'Office 365 Outlook',shared_teams:'Microsoft Teams',shared_onedriveforbusiness:'OneDrive for Business',shared_sharepointonline:'SharePoint',shared_commondataserviceforapps:'Microsoft Dataverse / AI Builder',shared_conversionservice:'Content Conversion'};
const get=(o,path)=>path.reduce((v,k)=>v!=null&&own(v,k)?v[k]:undefined,o);
function put(o,path,value){ let v=o;for(const k of path.slice(0,-1)){if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe property');if(v[k]==null)v[k]={};v=v[k];}const k=path.at(-1);if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe property');v[k]=value;}
const f=(label,path,type='text',required=false,hint='',options=null)=>({label,path,type,required,hint,options});
const p=(label,key,type='text',required=false,hint='',options=null)=>f(label,['inputs','parameters',key],type,required,hint,options);
const inp=(label,key,type='text',required=false,hint='',options=null)=>f(label,['inputs',key],type,required,hint,options);
function api(connector,operationId,parameters){return {type:'OpenApiConnection',inputs:{parameters,host:{apiId:API+connector,connectionName:connector,operationId},authentication:"@parameters('$authentication')"}};}
const catalog={};
function def(id,title,group,mark,description,make,fields,outs=[],note=''){catalog[id]={id,title,group,mark,description,make,fields,outs,note};}
const arrayHint='Use the reference picker for an array from an earlier step, or enter an expression.';
def('compose','Keep a value','Data','{ }','Store text, a calculation, an object, or a list.',()=>({type:'Compose',inputs:''}),[f('Value',['inputs'],'value',true,'Text by default. Use JSON mode for an object or array.')],[['Value','outputs']]);
def('parse','Read structured JSON','Data','{ }','Turn a JSON response into fields you can use.',()=>({type:'ParseJson',inputs:{content:'',schema:{type:'object',properties:{}}}}),[inp('JSON to read','content','value',true),inp('Expected structure','schema','json',true,'JSON Schema, not sample data. Use Generate schema to start from an example.')],[['Parsed data','body']]);
def('filter','Keep matching items','Data','≡','Filter a list using a condition.',()=>({type:'Query',inputs:{from:[],where:'@equals(item()?[\'status\'], \'Open\')'}}),[inp('List','from','value',true,arrayHint),inp('Keep item when','where','condition',true)],[['Filtered list','body']]);
def('select','Choose fields','Data','{ }','Reshape every item into a simpler object.',()=>({type:'Select',inputs:{from:[],select:{Name:"@item()?['name']"}}}),[inp('List','from','value',true,arrayHint),inp('Fields to keep','select','json',true,'Map output names to values. item() is the current list item.')],[['Reshaped list','body']]);
def('join','Join a list','Data','≡','Combine list items with a separator.',()=>({type:'Join',inputs:{from:[],joinWith:', '}}),[inp('List','from','value',true,arrayHint),inp('Separator','joinWith')],[['Joined text','body']]);
def('table','Make an HTML table','Data','▤','Create a table for an email from a list of objects.',()=>({type:'Table',inputs:{from:[],format:'HTML'}}),[inp('List of records','from','value',true,arrayHint)],[['HTML table','body']]);
def('initialize','Create a variable','Variables','◇','Create one named value at the top level.',()=>({type:'InitializeVariable',inputs:{variables:[{name:'MyValue',type:'string',value:''}]}}),[f('Variable name',['inputs','variables',0,'name'],'text',true),f('Type',['inputs','variables',0,'type'],'select',true,'',['string','integer','float','boolean','array','object']),f('Starting value',['inputs','variables',0,'value'],'value')],[],'Place variable initialization at the root, before a loop or condition.');
def('set','Replace a variable','Variables','◇','Replace the contents of an existing variable.',()=>({type:'SetVariable',inputs:{name:'',value:''}}),[inp('Variable','name','variable',true),inp('New value','value','value',true)]);
def('appendText','Add text to a variable','Variables','+','Append only the new text, not the old value again.',()=>({type:'AppendToStringVariable',inputs:{name:'',value:''}}),[inp('Text variable','name','variable',true),inp('Text to add','value','value',true)]);
def('appendArray','Add an item to a list','Variables','+','Collect one result in an existing array variable.',()=>({type:'AppendToArrayVariable',inputs:{name:'',value:''}}),[inp('Array variable','name','variable',true),inp('Item to add','value','value',true)]);
def('increment','Increase a counter','Variables','+1','Add a number to an integer or float variable.',()=>({type:'IncrementVariable',inputs:{name:'',value:1}}),[inp('Counter variable','name','variable',true),inp('Increase by','value','number',true)]);
def('loop','For each item','Logic','↻','Repeat a group of steps for every item in a list.',()=>({type:'Foreach',foreach:[],actions:{},runtimeConfiguration:{concurrency:{repetitions:1}}}),[f('Repeat for each item in',['foreach'],'value',true,arrayHint),f('Items at the same time',['runtimeConfiguration','concurrency','repetitions'],'number',false,'1 is sequential and safe for shared variables. Maximum 50.')],[],'Add steps inside this block. Sequential by default.');
def('condition','Only when / otherwise','Logic','⑂','Take different steps depending on a condition.',()=>({type:'If',expression:{equals:['','']},actions:{},else:{actions:{}}}),[f('Continue on the Yes branch when',['expression'],'condition',true)]);
def('scope','Group steps','Logic','▣','Keep steps together, including a try or catch group.',()=>({type:'Scope',actions:{}}),[],[],'Use Advanced > Run after on a second group to handle the first group failing.');
def('delay','Wait','Logic','◷','Wait before the next step.',()=>({type:'Wait',inputs:{interval:{count:1,unit:'Minute'}}}),[f('Wait for',['inputs','interval','count'],'number',true),f('Unit',['inputs','interval','unit'],'select',true,'',['Second','Minute','Hour','Day'])]);
def('stop','Stop the flow','Logic','■','Finish successfully or report a failure.',()=>({type:'Terminate',inputs:{runStatus:'Succeeded'}}),[inp('Final status','runStatus','select',true,'',['Succeeded','Failed','Cancelled'])]);
def('email','Send an email','Outlook','✉','Send a complete HTML email using Outlook.',()=>api('shared_office365','SendEmailV2',{'emailMessage/To':'','emailMessage/Subject':'Flowcraft briefing','emailMessage/Body':'','emailMessage/Importance':'Normal'}),[p('To','emailMessage/To','text',true,'Your work email address. Multiple recipients: separate with semicolons.'),p('Subject','emailMessage/Subject','text',true),p('Email body','emailMessage/Body','textarea',true,'HTML is supported. Use Insert value to include the output of another step.'),p('Importance','emailMessage/Importance','select',false,'',['Normal','High','Low'])],[],'This sends when Power Automate runs, not from this browser.');
def('getEmail','Read an email','Outlook','✉','Retrieve an email by its message ID.',()=>api('shared_office365','GetEmailV2',{messageId:'',includeAttachments:false}),[p('Message ID','messageId','text',true),p('Include attachment content','includeAttachments','boolean')],[['Email body','body','body'],['Subject','body','subject'],['Attachments','body','attachments'],['Message ID','body','id']]);
def('listEmail','Find emails','Outlook','≡','Read a bounded set of messages from a mail folder.',()=>api('shared_office365','GetEmailsV3',{folderPath:'Inbox',top:25,fetchOnlyUnread:false,includeAttachments:false}),[p('Folder','folderPath','text',true),p('Search query','searchQuery','text',false,'Outlook search syntax, for example received:today. Empty means no search filter.'),p('Maximum messages','top','number',true,'1 to 1000. This is a bounded result, not an exhaustive mailbox scan.'),p('Unread only','fetchOnlyUnread','boolean')],[['Messages','body','value']]);
def('attachment','Read an attachment','Outlook','⌁','Retrieve file content from an email attachment.',()=>api('shared_office365','GetAttachment_V2',{messageId:'',attachmentId:''}),[p('Parent message ID','messageId','text',true,'Use the email ID, not the attachment itself.'),p('Attachment ID','attachmentId','text',true,'Use the current attachment id, not contentBytes.')],[['Content (base64)','body','contentBytes'],['Filename','body','name']]);
def('outlookHttp','Outlook Graph request','Outlook','↗','Call the Microsoft Graph mail/calendar endpoints through Outlook.',()=>api('shared_office365','HttpRequest',{Uri:'https://graph.microsoft.com/v1.0/me/messages?$top=10',Method:'GET',ContentType:'application/json'}),[p('Graph URL','Uri','text',true),p('Method','Method','select',true,'',['GET','POST','PATCH','DELETE']),p('Body','Body','value'),p('Content type','ContentType')],[['Response','body']],'Only supported mail/calendar paths, not arbitrary Graph APIs.');
def('htmlText','HTML to plain text','Data','Aa','Convert email HTML to readable text.',()=>api('shared_conversionservice','HtmlToText',{Content:''}),[p('HTML content','Content','textarea',true)],[['Plain text','body']],'Does not read pixels or decode attached .msg files. Content Conversion is a preview connector.');
def('teams','Message me in Teams','Microsoft 365','▥','Post an HTML message as the Flow bot.',()=>api('shared_teams','PostMessageToConversation',{poster:'Flow bot',location:'Chat with Flow bot','body/recipient':'','body/messageBody':''}),[p('Recipient work email','body/recipient','text',true),p('Message','body/messageBody','textarea',true)],[['Message response','body']],'Use email for long reports. Teams has a message size limit.');
def('saveFile','Create a OneDrive file','Microsoft 365','▱','Write content into a new OneDrive for Business file.',()=>api('shared_onedriveforbusiness','CreateFile',{folderPath:'/',name:'report.html',body:''}),[p('Folder','folderPath','text',true,'The folder must already exist.'),p('Filename','name','text',true),p('Content','body','value',true,'For base64 attachment bytes, use base64ToBinary(...) rather than plain base64 text.')],[['File ID','body','Id'],['File path','body','Path']]);
def('readFile','Read a OneDrive file','Microsoft 365','▱','Get the contents of a file by its path.',()=>api('shared_onedriveforbusiness','GetFileContentByPath',{path:'',inferContentType:true}),[p('File path','path','text',true),p('Infer content type','inferContentType','boolean')],[['File contents','body']]);
def('sharepoint','Read SharePoint items','Microsoft 365','≡','Get records from an existing SharePoint list.',()=>api('shared_sharepointonline','GetItems',{dataset:'',table:''}),[p('Site URL','dataset','text',true),p('List ID','table','text',true,'The list GUID from your existing flow or SharePoint list settings.'),p('OData filter','$filter'),p('Maximum records','$top','number')],[['Items','body','value']]);
def('ai','Run a saved AI prompt','AI','✦','Use an existing AI Builder prompt and its real input names.',()=>api('shared_commondataserviceforapps','aibuilderpredict_customprompt',{recordId:''}),[p('Saved prompt ID','recordId','text',true,'Import an exported flow to reuse its real prompt ID. A name alone does not create a prompt.')],[['Response text','outputs','body/responsev2/predictionOutput/text'],['Full response','body']],'AI runs in Microsoft, consumes capacity, and needs a saved prompt in the destination environment. This ZIP does not package a new prompt.');
def('http','HTTP request','Advanced','↗','Call an HTTPS endpoint from the flow.',()=>({type:'Http',inputs:{method:'GET',uri:'',headers:{}}}),[inp('URL','uri','text',true),inp('Method','method','select',true,'',['GET','POST','PUT','PATCH','DELETE']),inp('Headers','headers','json'),inp('Body','body','value')],[['Response','body']],'Premium capability. Authentication, permissions, tenant policy and licensing still apply. Never put a secret in public examples.');
def('response','Respond to a request','Advanced','↩','Return a result to the caller of an HTTP-triggered flow.',()=>({type:'Response',kind:'Http',inputs:{statusCode:200,body:'OK'}}),[inp('Status code','statusCode','number',true),inp('Response body','body','value',true)],[['Response','body']]);
const triggers={
 manual:{title:'When I press a button',make:()=>({type:'Request',kind:'Button',inputs:{schema:{type:'object',properties:{}}}}),fields:[f('Optional input schema',['inputs','schema'],'json',true,'Leave the default for a button with no inputs.')]},
 mail:{title:'When an Outlook email arrives',make:()=>({type:'OpenApiConnectionNotification',splitOn:"@triggerOutputs()?['body/value']",inputs:{parameters:{folderPath:'Inbox',includeAttachments:false,fetchOnlyWithAttachment:false,subjectFilter:'Automate this'},host:{apiId:API+'shared_office365',connectionName:'shared_office365',operationId:'OnNewEmailV3'},authentication:"@parameters('$authentication')"}}),fields:[p('Subject contains','subjectFilter','text',false,'Keep this specific so the briefing does not trigger itself.'),p('Sender filter','from'),p('Folder','folderPath','text',false,'Defaults to Inbox when omitted.'),p('Only emails with attachments','fetchOnlyWithAttachment','boolean'),p('Include attachment bytes','includeAttachments','boolean')]},
 schedule:{title:'On a schedule',make:()=>({type:'Recurrence',recurrence:{frequency:'Day',interval:1,timeZone:'Eastern Standard Time',schedule:{hours:[8],minutes:[0]}}}),fields:[f('Frequency',['recurrence','frequency'],'select',true,'',['Minute','Hour','Day','Week']),f('Every',['recurrence','interval'],'number',true),f('Time zone',['recurrence','timeZone'],'text',true,'Windows time-zone ID, for example Eastern Standard Time or UTC.'),f('Schedule details',['recurrence','schedule'],'json',false,'For Day/Week: hours and minutes arrays. For Week add weekDays, for example ["Monday"].')]},
 request:{title:'When an HTTP request arrives',make:()=>({type:'Request',kind:'Http',inputs:{schema:{type:'object',properties:{}}}}),fields:[f('Request JSON schema',['inputs','schema'],'json',true)]}
};
function kind(a){if(!a)return 'unknown';for(const k of Object.keys(catalog)){const b=catalog[k].make();if(a.type!==b.type)continue;if(a.type==='OpenApiConnection'){if(a.inputs?.host?.operationId===b.inputs.host.operationId&&(a.inputs.host.apiId===b.inputs.host.apiId||k==='ai'))return k;}else return k;}return 'unknown';}
function triggerKind(a){if(a?.type==='Recurrence')return 'schedule';if(a?.inputs?.host?.operationId==='OnNewEmailV3')return 'mail';if(a?.kind==='Button')return 'manual';if(a?.type==='Request')return 'request';return 'unknown';}
function branches(a){const r=[];if(object(a.actions))r.push(['actions',a.type==='If'?'Yes':'Steps']);if(object(a.else?.actions))r.push(['else.actions','Otherwise']);if(object(a.cases))for(const k of Object.keys(a.cases))if(object(a.cases[k]?.actions))r.push([['cases',k,'actions'],'Case: '+k]);if(object(a.default?.actions))r.push(['default.actions','Default']);return r.map(([p,l])=>[Array.isArray(p)?p:p.split('.'),l]);}
function walk(definition){const rows=[];function visit(acts,path,ancestors){for(const [name,a] of Object.entries(acts||{})){rows.push({name,a,path:[...path,name],scope:path,ancestors});for(const [b] of branches(a))visit(get(a,b),[...path,name,...b],[...ancestors,name]);}}visit(definition.actions,['actions'],[]);return rows;}
function newProject(name='Hello, automation'){return {format:'flowcraft',version:1,name,description:'Built with Flowcraft',labels:{},connections:{},mode:'legacy',definition:{$schema:'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#',contentVersion:'1.0.0.0',parameters:{$authentication:{defaultValue:{},type:'SecureObject'},$connections:{defaultValue:{},type:'Object'}},triggers:{Start:triggers.manual.make()},actions:{},outputs:{}}};}
function register(p,a){const h=a.inputs?.host;if(!h)return;if(h.connectionName&&!p.connections[h.connectionName])p.connections[h.connectionName]={id:h.apiId,source:'Embedded'};}
function unique(p,title){const used=new Set([...walk(p.definition).map(x=>x.name),...Object.keys(p.definition.triggers)]);let b=title.replace(/[^a-zA-Z0-9_]/g,'_').replace(/_+/g,'_').slice(0,55)||'Step';let name=b,n=2;while([...used].some(x=>x.toLowerCase()===name.toLowerCase()))name=b+'_'+n++;return name;}
function linear(acts){const es=Object.entries(acts);return es.every(([n,a],i)=>{const r=a.runAfter||{};return i===0?!Object.keys(r).length:Object.keys(r).length===1&&own(r,es[i-1][0]);});}
function chain(acts,first={}){const out={};let prev;for(const [n,a] of Object.entries(acts)){a.runAfter=prev?{[prev]:['Succeeded']}:first;out[n]=a;prev=n;}return out;}
function add(p,id,scope=['actions'],after=null,label){const acts=get(p.definition,scope);if(!object(acts))throw Error('Choose a valid step group.');const a=catalog[id].make();register(p,a);if(id==='ai')a.metadata={flowSystemMetadata:{portalOperationId:'aibuilderpredict_customprompt',portalOperationGroup:'aibuilder',portalOperationApiDisplayNameOverride:'AI Builder'}};const name=unique(p,label||catalog[id].title);p.labels[name]=label||catalog[id].title;
 const es=Object.entries(acts);if(after&&own(acts,after)){if(!linear(acts))throw Error('This group has custom dependencies. Add at the end, or edit its raw dependencies without flattening the graph.');const i=es.findIndex(([n])=>n===after);const next=es[i+1];a.runAfter={[after]:['Succeeded']};es.splice(i+1,0,[name,a]);if(next){const flags=next[1].runAfter[after];next[1].runAfter={[name]:flags};}put(p.definition,scope,Object.fromEntries(es));}
 else{const depended=new Set(es.flatMap(([,a])=>Object.keys(a.runAfter||{})));a.runAfter=Object.fromEntries(es.filter(([n])=>!depended.has(n)).map(([n])=>[n,['Succeeded']]));acts[name]=a;}return name;}
function locate(p,name){return walk(p.definition).find(x=>x.name===name);}
function move(p,name,direction){const n=locate(p,name);if(!n)return false;const acts=get(p.definition,n.scope);if(!linear(acts))throw Error('Custom dependencies are preserved. Reordering is available only for a simple sequence.');if(Object.values(acts).some(a=>Object.values(a.runAfter||{}).some(v=>j(v)!==j(['Succeeded']))))throw Error('This sequence has failure/skip handling. Edit dependencies explicitly instead of reordering.');const es=Object.entries(acts),i=es.findIndex(([k])=>k===name),t=i+direction;if(t<0||t>=es.length)return false;[es[i],es[t]]=[es[t],es[i]];put(p.definition,n.scope,chain(Object.fromEntries(es)));return true;}
function remove(p,name){const n=locate(p,name);if(!n)return;const acts=get(p.definition,n.scope),pre=n.a.runAfter||{};for(const [k,a] of Object.entries(acts)){if(k!==name&&own(a.runAfter||{},name)){delete a.runAfter[name];Object.assign(a.runAfter,clone(pre));}}delete acts[name];delete p.labels[name];}
function duplicate(p,name){const n=locate(p,name);if(!n)return;const acts=get(p.definition,n.scope);if(!linear(acts))throw Error('Duplicate is available only in a simple sequence.');let a=clone(n.a);function allChildren(x){let ns=[];for(const [path] of branches(x))for(const [k,v] of Object.entries(get(x,path))){ns.push(k,...allChildren(v));}return ns;}
 const map={};const reserved=new Set(walk(p.definition).map(x=>x.name));for(const old of [name,...allChildren(a)]){let base=old+'_copy',nn=base,i=2;while(reserved.has(nn))nn=base+'_'+i++;reserved.add(nn);map[old]=nn;}
 function remap(v){if(typeof v==='string')return v.replace(/\b(outputs|body|actions|result|items)\('([^']+)'\)/g,(m,fn,id)=>map[id]?`${fn}('${map[id]}')`:m);if(Array.isArray(v))return v.map(remap);if(object(v)){const r={};for(const [k,x] of Object.entries(v))r[map[k]||k]=remap(x);return r;}return v;}
 a=remap(a);a.runAfter={[name]:['Succeeded']};const es=Object.entries(acts),i=es.findIndex(([k])=>k===name);if(es[i+1]){const old=es[i+1][1].runAfter[name];es[i+1][1].runAfter={[map[name]]:old};}es.splice(i+1,0,[map[name],a]);put(p.definition,n.scope,Object.fromEntries(es));for(const [old,nn] of Object.entries(map))p.labels[nn]=(p.labels[old]||old)+' copy';return map[name];}
function switchTrigger(p,k){const old=Object.keys(p.definition.triggers)[0]||'Start';p.definition.triggers={[old]:triggers[k].make()};register(p,p.definition.triggers[old]);}
function schemaFrom(sample){if(sample===null)return {type:['string','null']};if(Array.isArray(sample))return {type:'array',items:sample.length?schemaFrom(sample[0]):{}};if(object(sample))return {type:'object',properties:Object.fromEntries(Object.entries(sample).map(([k,v])=>[k,schemaFrom(v)]))};return {type:typeof sample==='number'?(Number.isInteger(sample)?'integer':'number'):typeof sample};}
const out=(name,method='outputs',path)=>`@${method}('${name}')${path?`?['${path}']`:''}`;
function refs(p,name){const rows=walk(p.definition),current=rows.find(r=>r.name===name),seen=new Set(),res=[];const tk=triggerKind(Object.values(p.definition.triggers)[0]);const tr=tk==='mail'?[['Email body','body'],['Email subject','subject'],['Sender','from'],['Message ID','id'],['Attachments','attachments'],['Received time','receivedDateTime']]:[['Trigger data',null]];for(const [label,path] of tr)res.push({group:'Trigger',label,value:path?`@triggerBody()?['${path}']`:'@triggerBody()'});
 const allowed=new Set();if(current){let path=current.scope,child=name;while(path.length){const acts=get(p.definition,path);function collect(n){for(const dep of Object.keys(acts[n]?.runAfter||{})){if(!allowed.has(dep)){allowed.add(dep);collect(dep);}}}collect(child);if(path.length===1)break;const ancestor=rows.filter(r=>r.path.length<path.length&&r.path.every((v,i)=>path[i]===v)).at(-1);if(!ancestor)break;child=ancestor.name;path=ancestor.scope;}}
 for(const r of rows){if(!allowed.has(r.name))continue;const c=catalog[kind(r.a)];for(const [label,method,path] of c?.outs||[['Output','outputs']])res.push({group:p.labels[r.name]||r.name,label,value:out(r.name,method,path)});if(r.a.type==='InitializeVariable')for(const v of r.a.inputs.variables)res.push({group:'Variables',label:v.name,value:`@variables('${v.name}')`});}
 if(current){for(const anc of current.ancestors){const a=locate(p,anc);if(a?.a.type==='Foreach'){res.push({group:'Current loop item',label:p.labels[anc]||anc,value:`@items('${anc}')`});for(const key of ['id','name','subject','body','contentBytes'])res.push({group:'Current loop item',label:key,value:`@items('${anc}')?['${key}']`});}}if(['Query','Select'].includes(current.a.type))res.push({group:'Current list item',label:'Item',value:'@item()'});}
 return res.filter(x=>{if(seen.has(x.value))return false;seen.add(x.value);return true;});}
function strings(v,path=[],r=[]){if(typeof v==='string')r.push([v,path]);else if(Array.isArray(v))v.forEach((x,i)=>strings(x,[...path,i],r));else if(object(v))for(const [k,x] of Object.entries(v))strings(x,[...path,k],r);return r;}
function exprBalanced(s){if(!s.startsWith('@')&&!s.includes('@{'))return true;if(s.startsWith('@@'))return true;const chunks=[];if(s.startsWith('@')&&!s.startsWith('@{'))chunks.push(s.slice(1));else{const rx=/@\{/g;let m;while((m=rx.exec(s))){let q=false,depth=1,i=rx.lastIndex;for(;i<s.length;i++){if(s[i]==="'"){if(q&&s[i+1]==="'"){i++;continue;}q=!q;}if(!q){if(s[i]==='{')depth++;if(s[i]==='}'&&--depth===0)break;}}if(depth!==0)return false;chunks.push(s.slice(rx.lastIndex,i));rx.lastIndex=i+1;}}
 return chunks.every(c=>{const st=[];let q=false;for(let i=0;i<c.length;i++){const x=c[i];if(x==="'"){if(q&&c[i+1]==="'"){i++;continue;}q=!q;continue;}if(q)continue;if('([{'.includes(x))st.push(x);if(')]}'.includes(x)){const match={')':'(',']':'[','}':'{'};if(st.pop()!==match[x])return false;}}return !q&&!st.length;});}
function usedConnections(p){const found={};for(const a of [...Object.values(p.definition.triggers),...walk(p.definition).map(x=>x.a)]){const h=a.inputs?.host;if(h?.connectionName){const r=p.connections[h.connectionName];found[h.connectionName]=r||{id:h.apiId,source:'Embedded'};}}return found;}
function validate(p){const issues=[],emit=(severity,node,text)=>issues.push({severity,node,text});const d=p.definition;if(!p.name?.trim())emit('error',null,'Give the flow a name.');if(!object(d)||!object(d.actions)||!object(d.triggers))return [{severity:'error',text:'Invalid workflow definition.'}];if(Object.keys(d.triggers).length!==1)emit('error',null,'A flow needs exactly one trigger.');const rows=walk(d),names=new Set(rows.map(r=>r.name));if(rows.length>500)emit('error',null,'More than 500 actions. Split this workflow.');if(!rows.length)emit('warning',null,'This flow has no actions yet.');if(new Set(rows.map(r=>r.name.toLowerCase())).size!==rows.length)emit('error',null,'Action names must be unique across the whole flow.');
 function deps(acts){const done=new Set(),busy=new Set();function v(n){if(busy.has(n)){emit('error',n,'Circular run-after dependency.');return;}if(done.has(n))return;busy.add(n);for(const [dep,flags] of Object.entries(acts[n]?.runAfter||{})){if(!own(acts,dep)){emit('error',n,`Run-after target ${dep} is not in this group.`);continue;}if(!Array.isArray(flags)||!flags.length||flags.some(x=>!['Succeeded','Failed','Skipped','TimedOut'].includes(x)))emit('error',n,'Invalid run-after status.');v(dep);}busy.delete(n);done.add(n);}for(const n of Object.keys(acts))v(n);}
 deps(d.actions);for(const r of rows)for(const [path] of branches(r.a))deps(get(r.a,path));
 const initialized={};for(const r of rows)if(r.a.type==='InitializeVariable'){const vs=r.a.inputs?.variables||[];if(vs.length!==1)emit('error',r.name,'Initialize exactly one variable in each action.');if(r.ancestors.length)emit('error',r.name,'Create this variable at the root, outside every loop, condition, and group.');for(const v of vs){if(!v.name)emit('error',r.name,'Variable name is required.');if(initialized[v.name])emit('error',r.name,'Variable is initialized more than once: '+v.name);initialized[v.name]={...v,node:r.name};const t=v.type, val=v.value;const expression=typeof val==='string'&&val.startsWith('@');if(!expression&&val!==undefined){const valid={string:typeof val==='string',integer:Number.isInteger(val),float:typeof val==='number',boolean:typeof val==='boolean',array:Array.isArray(val),object:object(val)};if(!valid[t])emit('error',r.name,`Starting value must be ${t}. Change its value mode as well as its type.`);}}}
 const checkFields=(a,c,n)=>{for(const field of c?.fields||[]){const v=get(a,field.path);if(field.required&&(v===undefined||v===null||typeof v==='string'&&!v.trim()))emit('error',n,`${field.label} is empty.`);} };
 const trig=Object.values(d.triggers)[0],tk=triggerKind(trig);checkFields(trig,triggers[tk],null);if(tk==='unknown')emit('warning',null,'Unknown trigger preserved. Review its raw definition and tenant requirements.');if(tk==='request')emit('warning',null,'HTTP trigger: configure and verify caller authentication in Power Automate before enabling.');if(tk==='schedule'){const rec=trig.recurrence||{};if(!Number.isInteger(rec.interval)||rec.interval<1)emit('error',null,'Schedule interval must be a positive integer.');if(['Minute','Hour'].includes(rec.frequency)&&rec.schedule)emit('error',null,'Remove schedule details when using Minute or Hour frequency.');if(rec.schedule?.hours?.some(x=>!Number.isInteger(x)||x<0||x>23)||rec.schedule?.minutes?.some(x=>!Number.isInteger(x)||x<0||x>59))emit('error',null,'Schedule hours must be 0-23 and minutes 0-59.');}
 for(const r of rows){const {name,a}=r,k=kind(a),c=catalog[k];checkFields(a,c,name);if(!c)emit('warning',name,'Unsupported step is preserved as raw JSON, not converted or dropped.');
  if(k==='loop'){const rep=a.runtimeConfiguration?.concurrency?.repetitions;if(rep!=null&&(!Number.isInteger(rep)||rep<1||rep>50))emit('error',name,'Loop concurrency must be an integer from 1 to 50.');if(Array.isArray(a.foreach)&&!a.foreach.length)emit('warning',name,'This loop currently has an empty list and will run zero times.');if(!Object.keys(a.actions||{}).length)emit('warning',name,'Add at least one step inside this loop.');}
  if(k==='condition'){const vals=a.expression?.equals;if(vals&&vals.every(x=>x===''))emit('error',name,'Choose the two values for the condition.');}
  if(k==='stop'&&r.ancestors.some(n=>locate(p,n)?.a.type==='Foreach'))emit('error',name,'Terminate cannot be placed inside a for-each loop.');
  if(k==='response'&&tk!=='request')emit('error',name,'Response requires an HTTP request trigger.');
  if(['http','outlookHttp'].includes(k)){const u=k==='http'?a.inputs.uri:a.inputs.parameters.Uri;if(u&&!u.startsWith('@')&&!/^https:\/\//i.test(u))emit('error',name,'Use an HTTPS URL or an expression.');if(k==='http')emit('warning',name,'HTTP requires appropriate premium licensing and configured authentication.');if(k==='outlookHttp'&&u&&!u.startsWith('@')&&!/^https:\/\/graph\.microsoft\.com\/(v1\.0|beta)\/(me|users\/[^/]+)\/(messages|mailFolders|events|calendar|calendars|outlook|inferenceClassification)(\/|\?|$)/.test(u))emit('error',name,'Outlook Graph supports mail/calendar paths, not this endpoint.');}
  if(k==='ai'){const id=a.inputs.parameters.recordId;if(id&&!/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(id))emit('error',name,'Use a real saved prompt GUID, not its display name.');if(id&&(/^0{8}-0{4}-0{4}-0{4}-/.test(id)||/^(0|-)+$/.test(id)))emit('error',name,'Placeholder prompt IDs cannot be imported.');emit('warning',name,'The saved prompt must exist in the target environment. AI capacity and the input schema are not checked locally.');if(!Object.keys(a.inputs.parameters).some(k=>k.startsWith('item/requestv2/')))emit('warning',name,'No input values are mapped to this prompt. Static prompts may not need inputs.');}
  if(k==='teams'){const body=a.inputs.parameters['body/messageBody']||'';if(new TextEncoder().encode(body).length>24000)emit('error',name,'Static Teams message is too large for this safety budget. Use an email instead.');else emit('warning',name,'Dynamic Teams message size is only known at runtime. Keep long drafts in email.');}
  if(['email','teams'].includes(k)){const to=a.inputs.parameters[k==='email'?'emailMessage/To':'body/recipient'];if(to&&!to.includes('@{')&&!to.startsWith('@')&&to.split(';').some(s=>!/^\s*[^\s@]+@[^\s@]+\.[^\s@]+\s*$/.test(s)))emit('error',name,'Enter a valid recipient address, not "me".');}
  if(k==='email'&&tk==='mail'){const subject=a.inputs.parameters['emailMessage/Subject']||'',filter=trig.inputs.parameters.subjectFilter||'';if(!filter||subject.toLowerCase().includes(filter.toLowerCase()))emit('warning',name,'This outgoing email could match the incoming-mail trigger. Use a distinct subject filter or sender condition to prevent a loop.');}
  if(k==='listEmail'){const top=a.inputs.parameters.top;if(!Number.isInteger(top)||top<1||top>1000)emit('error',name,'Maximum messages must be an integer from 1 to 1000.');emit('warning',name,'The email query is bounded by its maximum count. It is not guaranteed to include every matching message.');}
  if(k==='parse'&&!object(a.inputs.schema))emit('error',name,'Expected structure must be a JSON Schema object.');
  const mutations=['SetVariable','AppendToStringVariable','AppendToArrayVariable','IncrementVariable','DecrementVariable'];if(mutations.includes(a.type)){const vn=a.inputs.name,init=initialized[vn];if(!init)emit('error',name,'Variable has not been created: '+vn);else{const allowed=refs(p,name).some(x=>x.value===`@variables('${vn}')`);if(!allowed)emit('error',name,'Variable must be initialized on a prior guaranteed path: '+vn);if(a.type==='SetVariable'&&init.type==='array'&&typeof a.inputs.value!=='string'&&!Array.isArray(a.inputs.value))emit('error',name,'New value must be an array or an expression.');if(a.type==='AppendToStringVariable'&&init.type!=='string'||a.type==='AppendToArrayVariable'&&init.type!=='array')emit('error',name,'The variable type does not match this append action.');if(['IncrementVariable','DecrementVariable'].includes(a.type)&&!['integer','float'].includes(init.type))emit('error',name,'A counter must be an integer or float variable.');}if(strings(a.inputs.value).some(([s])=>s.includes(`variables('${vn}')`)))emit('error',name,'Do not reference this variable in its own update. Append only new text, or calculate the replacement in a separate Compose step.');for(const an of r.ancestors){const parent=locate(p,an)?.a;if(parent?.type==='Foreach'&&(parent.runtimeConfiguration?.concurrency?.repetitions??1)>1)emit('error',name,'Shared variable update inside a concurrent loop. Set items at the same time to 1.');}}
  for(const [s,path] of strings({inputs:a.inputs,foreach:a.foreach,expression:a.expression})){if(!exprBalanced(s))emit('error',name,'Unbalanced expression brackets or quotes.');if(/\{\{(?:EmailBody|TaskPayload|\w+)\}\}/.test(s))emit('warning',name,'Double braces are plain text, not a Power Automate input binding. Use Insert value.');if((s.startsWith('@')||s.includes('@{'))&&!s.startsWith('@@')){for(const m of s.matchAll(/\b(outputs|body|actions|result|items)\('([^']+)'\)/g)){if(!names.has(m[2]))emit('error',name,'Reference points to a missing action: '+m[2]);else if(m[2]===name)emit('error',name,'This action references itself.');else if(m[1]==='items'&&!r.ancestors.includes(m[2]))emit('error',name,'Current-item reference is outside its loop: '+m[2]);else if(['outputs','body'].includes(m[1])){const src=locate(p,m[2]);const sourceLoops=src.ancestors.filter(n=>locate(p,n)?.a.type==='Foreach');if(sourceLoops.some(n=>!r.ancestors.includes(n)))emit('error',name,'Output from inside a loop is used outside it. Collect results sequentially into an array.');else{const available=refs(p,name).some(x=>x.value.startsWith(`@outputs('${m[2]}')`)||x.value.startsWith(`@body('${m[2]}')`));if(!available){const reachable=src.ancestors.some(ancestor=>refs(p,name).some(x=>x.value.startsWith(`@outputs('${ancestor}')`)||x.value.startsWith(`@body('${ancestor}')`)));if(reachable)emit('warning',name,'Referenced output is inside a group or branch and may be skipped: '+m[2]);else emit('error',name,'Referenced step does not run before this step: '+m[2]);}}}}for(const m of s.matchAll(/\bvariables\('([^']+)'\)/g))if(!initialized[m[1]])emit('error',name,'Missing variable: '+m[1]);if(/\bresult\(/.test(s))emit('warning',name,'result() output shape depends on the action. This local checker does not verify its runtime aggregation.');}}
  const h=a.inputs?.host;if(h?.connectionName&&!p.connections[h.connectionName])emit('error',name,'Missing connector binding: '+h.connectionName);
 }
 for(const [key,r] of Object.entries(usedConnections(p)))if(!r.id?.startsWith(API)&&!r.api?.name)emit('error',null,'Connector '+key+' needs a valid API ID.');
 return issues.filter((x,i,all)=>all.findIndex(y=>y.severity===x.severity&&y.node===x.node&&y.text===x.text)===i);
}
function packageFiles(p){const problems=validate(p).filter(x=>x.severity==='error');if(problems.length)throw Error('Resolve '+problems.length+' error(s) before exporting.');if(p.mode!=='legacy')throw Error('Only legacy flow export is supported in this version.');const flow=uid(),resources={},cr={},am={},cm={},dependencies=[];for(const [key,ref] of Object.entries(usedConnections(p))){const apiId=ref.id||API+ref.api.name,apiName=apiId.split('/').at(-1),ar=uid(),conn=uid(),display=connectors[apiName]||apiName;resources[ar]={id:apiId,name:apiName,type:'Microsoft.PowerApps/apis',suggestedCreationType:'Existing',details:{displayName:display},configurableBy:'System',hierarchy:'Child',dependsOn:[]};resources[conn]={type:'Microsoft.PowerApps/apis/connections',suggestedCreationType:'Existing',creationType:'Existing',details:{displayName:display},configurableBy:'User',hierarchy:'Child',dependsOn:[ar]};dependencies.push(ar,conn);am[key]=ar;cm[key]=conn;cr[key]={connectionName:uid().replace(/-/g,''),source:'Embedded',id:apiId,tier:'NotSpecified',apiName:apiName.replace(/^shared_/,''),isProcessSimpleApiReferenceConversionAlreadyDone:false};}
 resources[flow]={type:'Microsoft.Flow/flows',suggestedCreationType:'New',creationType:'Existing, New, Update',details:{displayName:p.name},configurableBy:'User',hierarchy:'Root',dependsOn:dependencies};const base='Microsoft.Flow/flows/'+flow+'/';const d=clone(p.definition);d.parameters??={};d.parameters.$authentication??={defaultValue:{},type:'SecureObject'};d.parameters.$connections??={defaultValue:{},type:'Object'};
 return {'manifest.json':j({schema:'1.0',details:{displayName:p.name,description:p.description||'',createdTime:new Date().toISOString(),packageTelemetryId:uid(),creator:'N/A',sourceEnvironment:''},resources}),'Microsoft.Flow/flows/manifest.json':j({packageSchemaVersion:'1.0',flowAssets:{assetPaths:[flow]}}),[base+'definition.json']:j({name:flow,id:'/providers/Microsoft.Flow/flows/'+flow,type:'Microsoft.Flow/flows',properties:{apiId:API+'shared_logicflows',displayName:p.name,definition:d,connectionReferences:cr,flowFailureAlertSubscribed:false,isManaged:false}}),[base+'apisMap.json']:j(am),[base+'connectionsMap.json']:j(cm)};
}
function assertProject(p){if(!object(p)||p.format!=='flowcraft'||p.version!==1||!object(p.definition)||!object(p.definition.actions)||!object(p.definition.triggers))throw Error('This is not a Flowcraft v1 project.');const queue=[[p,0]];let count=0;while(queue.length){const [v,depth]=queue.pop();if(depth>60||++count>200000)throw Error('Project is too deeply nested or too large.');if(object(v)||Array.isArray(v))for(const [key,x] of Object.entries(v)){if(['__proto__','constructor','prototype'].includes(key))throw Error('Unsafe object key in imported project.');if(typeof x==='object'&&x)queue.push([x,depth+1]);}}if(walk(p.definition).length>1000)throw Error('Import is limited to 1000 actions.');p.labels??={};p.connections??={};p.mode??='legacy';return p;}
function importLegacy(files){if(files['solution.xml'])throw Error('This is a Power Platform Solution ZIP. Version 1 edits legacy flow packages, not AI model components. In Power Automate, export a non-solution flow as Package (.zip). Your current work has not changed.');const paths=Object.keys(files).filter(k=>/^Microsoft\.Flow\/flows\/[^/]+\/definition\.json$/.test(k));if(paths.length!==1)throw Error('Select a legacy package containing exactly one flow.');const data=JSON.parse(files[paths[0]]),props=data.properties,d=props?.definition;if(!object(d?.actions)||!object(d?.triggers))throw Error('This package has no readable workflow definition.');const p=newProject(props.displayName||'Imported flow');p.definition=clone(d);p.connections=clone(props.connectionReferences||{});assertProject(p);p.description=files['manifest.json']?JSON.parse(files['manifest.json']).details?.description||'':'';p.imported=true;for(const row of walk(d))p.labels[row.name]=row.name.replace(/_/g,' ');return assertProject(p);}
const recipes=[
 {id:'hello',title:'Hello, automation',tag:'Start here',desc:'A button, a message, and an email. One field to fill in.',needs:'Your email address'},
 {id:'summary',title:'Email → AI → email',tag:'AI',desc:'Summarize matching incoming emails and send yourself the result.',needs:'Recipient + a real saved prompt ID'},
 {id:'attachments',title:'Save email attachments',tag:'Files',desc:'Read every non-inline attachment and save it to OneDrive.',needs:'Subject filter + existing OneDrive folder'},
 {id:'digest',title:'Morning inbox digest',tag:'Scheduled',desc:'Find today’s emails, choose fields, and email an HTML table.',needs:'Recipient + schedule'},
 {id:'records',title:'Filter a list → report',tag:'Data',desc:'Keep matching sample records and turn them into an email table.',needs:'Recipient + your records'},
 {id:'perItem',title:'Analyze each item',tag:'AI + loop',desc:'Run a saved prompt for each record and collect results safely.',needs:'Recipient + saved prompt ID + prompt input name'},
 {id:'routing',title:'Only when it matters',tag:'Branches',desc:'Check an email subject and choose between two branches.',needs:'Subject filter + recipient'},
 {id:'catch',title:'Try / catch with alert',tag:'Resilience',desc:'Group work and send an email only when the group fails.',needs:'Recipient + the actions you want to protect'},
 {id:'blank',title:'Start from scratch',tag:'Blank',desc:'Choose a trigger and add exactly the steps you need.',needs:'Nothing yet'}
];
function recipe(id){const p=newProject(recipes.find(x=>x.id===id)?.title||'My flow');const addAt=(k,label,scope=['actions'])=>{const name=add(p,k,scope,null,label);return [name,get(p.definition,[...scope,name])];};const setEmail=(a,body,subject='Flowcraft briefing')=>Object.assign(a.inputs.parameters,{'emailMessage/Body':body,'emailMessage/Subject':subject});
 if(id==='hello'){const [n,a]=addAt('compose','Write a welcome message');a.inputs='<h2>Hello, automation.</h2><p>Your Flowcraft flow ran successfully.</p>';const [,e]=addAt('email','Email me the result');setEmail(e,out(n),'My first Flowcraft email');}
 if(id==='summary'){switchTrigger(p,'mail');const [t]=addAt('htmlText','Read the email text');p.definition.actions[t].inputs.parameters.Content='@triggerBody()?[\'body\']';const [ai,a]=addAt('ai','Summarize the email');a.inputs.parameters['item/requestv2/EmailBody']=out(t,'body');const [,e]=addAt('email','Email me the summary');setEmail(e,out(ai,'outputs','body/responsev2/predictionOutput/text'),'My AI briefing');}
 if(id==='attachments'){switchTrigger(p,'mail');Object.assign(Object.values(p.definition.triggers)[0].inputs.parameters,{includeAttachments:false,fetchOnlyWithAttachment:true});const [filter,f]=addAt('filter','Ignore inline signature images');f.inputs={from:"@triggerBody()?['attachments']",where:"@not(equals(item()?['isInline'], true))"};const [loop,l]=addAt('loop','For each attachment');l.foreach=out(filter,'body');const [read,r]=addAt('attachment','Get the file',['actions',loop,'actions']);r.inputs.parameters={messageId:"@triggerBody()?['id']",attachmentId:`@items('${loop}')?['id']`};const [,s]=addAt('saveFile','Save to OneDrive',['actions',loop,'actions']);s.inputs.parameters={folderPath:'/',name:`@items('${loop}')?['name']`,body:`@base64ToBinary(body('${read}')?['contentBytes'])`};}
 if(id==='digest'){switchTrigger(p,'schedule');const [list,l]=addAt('listEmail','Find today’s messages');l.inputs.parameters.searchQuery='received:today';l.inputs.parameters.top=100;const [sel,s]=addAt('select','Choose email fields');s.inputs={from:out(list,'body','value'),select:{Subject:"@item()?['subject']",From:"@item()?['from']",Received:"@item()?['receivedDateTime']"}};const [tab,t]=addAt('table','Build the digest table');t.inputs.from=out(sel,'body');const [,e]=addAt('email','Send the digest');setEmail(e,out(tab,'body'),'My inbox digest');}
 if(id==='records'||id==='perItem'){const [list,l]=addAt('compose','My records');l.inputs=[{name:'Review the plan',status:'Open'},{name:'Confirm receipt',status:'Closed'},{name:'Check the contract',status:'Open'}];if(id==='records'){const [fi,f]=addAt('filter','Keep open records');f.inputs.from=out(list);const [tb,t]=addAt('table','Make the report');t.inputs.from=out(fi,'body');const [,e]=addAt('email','Email the report');setEmail(e,out(tb,'body'),'My record report');}else{const [,v]=addAt('initialize','Create results list');v.inputs.variables=[{name:'Results',type:'array',value:[]}];const [lo,l]=addAt('loop','Analyze one record at a time');l.foreach=out(list);const [ai,a]=addAt('ai','Analyze this record',['actions',lo,'actions']);a.inputs.parameters['item/requestv2/TaskPayload']=`@string(items('${lo}'))`;const [,ap]=addAt('appendArray','Collect the result',['actions',lo,'actions']);ap.inputs={name:'Results',value:{Analysis:out(ai,'outputs','body/responsev2/predictionOutput/text')}};const [tb,t]=addAt('table','Make the results table');t.inputs.from="@variables('Results')";const [,e]=addAt('email','Email all results');setEmail(e,out(tb,'body'),'My AI results');}}
 if(id==='routing'){switchTrigger(p,'mail');const [c,a]=addAt('condition','Is this urgent?');a.expression={contains:["@toLower(triggerBody()?['subject'])",'urgent']};const [,e]=addAt('email','Notify me',['actions',c,'actions']);setEmail(e,"@triggerBody()?['body']",'Urgent email briefing');const [,v]=addAt('compose','No notification needed',['actions',c,'else','actions']);v.inputs='No urgent match.';}
 if(id==='catch'){const [s]=addAt('scope','Work to protect');const [,v]=addAt('compose','Replace this with your work',['actions',s,'actions']);v.inputs='Add your processing steps to this group.';const [ca,c]=addAt('scope','If the work fails');c.runAfter={[s]:['Failed','TimedOut']};const [,e]=addAt('email','Tell me what failed',['actions',ca,'actions']);setEmail(e,`<p>The work group failed. Check the first failed action in Power Automate run history.</p><p>Run: @{workflow()?['run']?['name']}</p>`,'Automation needs attention');}
 return p;
}
root.FlowCore={clone,own,object,uid,j,get,put,catalog,triggers,kind,triggerKind,branches,walk,newProject,register,add,locate,linear,move,remove,duplicate,switchTrigger,schemaFrom,refs,validate,usedConnections,packageFiles,importLegacy,assertProject,recipes,recipe,connectors,exprBalanced};
})(globalThis);
