/* Small bounded ZIP codec: STORE export, STORE/DEFLATE import. No network or dependencies. */
(function(root){
'use strict';
const enc=new TextEncoder(),dec=new TextDecoder('utf-8',{fatal:true}),LIMIT=25*1024*1024;
const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(bytes){let n=0xffffffff;for(const b of bytes)n=table[(n^b)&255]^(n>>>8);return (n^0xffffffff)>>>0;}
const safe=n=>n.length>0&&n.length<512&&!n.startsWith('/')&&!n.includes('\\')&&!n.includes('\0')&&!n.split('/').includes('..');
function concat(chunks){const size=chunks.reduce((n,c)=>n+c.length,0),v=new Uint8Array(size);let at=0;for(const c of chunks){v.set(c,at);at+=c.length;}return v;}
function store(files){const locals=[],centrals=[];let at=0;const now=new Date(),date=((Math.max(1980,now.getFullYear())-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate(),time=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1);const entries=Object.entries(files);if(entries.length>1000)throw Error('Too many ZIP entries.');for(const [name,value] of entries){if(!safe(name))throw Error('Unsafe ZIP filename.');const n=enc.encode(name),bytes=typeof value==='string'?enc.encode(value):value;if(!(bytes instanceof Uint8Array))throw Error('Invalid ZIP content.');if(bytes.length>LIMIT||at+bytes.length>LIMIT)throw Error('Export exceeds 25 MB.');const crc=crc32(bytes),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(10,time,true);v.setUint16(12,date,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);h.set(n,30);locals.push(h,bytes);const c=new Uint8Array(46+n.length),w=new DataView(c.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint16(12,time,true);w.setUint16(14,date,true);w.setUint32(16,crc,true);w.setUint32(20,bytes.length,true);w.setUint32(24,bytes.length,true);w.setUint16(28,n.length,true);w.setUint32(42,at,true);c.set(n,46);centrals.push(c);at+=h.length+bytes.length;}
 const central=concat(centrals),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,central.length,true);v.setUint32(16,at,true);return concat([...locals,central,end]);}
async function inflate(data,max){if(!root.DecompressionStream)throw Error('Compressed ZIP import needs a current version of Edge, Chrome, or Firefox. Uncompressed exports work without it.');let ds;try{ds=new DecompressionStream('deflate-raw');}catch{throw Error('This browser cannot decompress flow packages. Use current Edge or Chrome.');}const reader=new Blob([data]).stream().pipeThrough(ds).getReader(),chunks=[];let n=0;try{while(true){const {done,value}=await reader.read();if(done)break;n+=value.length;if(n>max){await reader.cancel();throw Error('Expanded ZIP content exceeds the safety limit.');}chunks.push(value);}}catch(e){try{await reader.cancel();}catch{}throw e;}return concat(chunks);}
async function read(input){const data=input instanceof Uint8Array?input:new Uint8Array(input);if(data.length>LIMIT)throw Error('ZIP import is limited to 25 MB.');const v=new DataView(data.buffer,data.byteOffset,data.byteLength);const range=(o,l)=>{if(o<0||l<0||o+l>data.length)throw Error('Truncated ZIP.');};const u16=o=>{range(o,2);return v.getUint16(o,true);},u32=o=>{range(o,4);return v.getUint32(o,true);};let end=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i--){if(u32(i)===0x06054b50&&i+22+u16(i+20)===data.length){end=i;break;}}if(end<0)throw Error('Not a readable ZIP archive.');if(u16(end+4)||u16(end+6)||u16(end+8)!==u16(end+10))throw Error('Multi-disk ZIP files are not supported.');const count=u16(end+10),size=u32(end+12),offset=u32(end+16);if(count>1000||count===65535||offset===0xffffffff||size===0xffffffff)throw Error('Large or ZIP64 archives are not supported.');if(offset+size>end)throw Error('Invalid ZIP directory.');let pos=offset,total=0;const files=Object.create(null);for(let i=0;i<count;i++){range(pos,46);if(u32(pos)!==0x02014b50)throw Error('Invalid ZIP directory entry.');const flags=u16(pos+8),method=u16(pos+10),crc=u32(pos+16),compressed=u32(pos+20),expanded=u32(pos+24),nl=u16(pos+28),el=u16(pos+30),cl=u16(pos+32),local=u32(pos+42);range(pos+46,nl+el+cl);const name=dec.decode(data.subarray(pos+46,pos+46+nl));pos+=46+nl+el+cl;if(!safe(name)||Object.hasOwn(files,name))throw Error('Unsafe or duplicate ZIP filename.');if(flags&1)throw Error('Encrypted ZIP files cannot be opened.');if(![0,8].includes(method))throw Error('Unsupported ZIP compression method: '+method);total+=expanded;if(expanded>LIMIT||total>LIMIT)throw Error('Expanded ZIP is larger than 25 MB.');range(local,30);if(u32(local)!==0x04034b50||u16(local+8)!==method)throw Error('Invalid local ZIP header.');const lnl=u16(local+26),lel=u16(local+28);range(local+30,lnl+lel);if(dec.decode(data.subarray(local+30,local+30+lnl))!==name)throw Error('ZIP filename mismatch.');const start=local+30+lnl+lel;range(start,compressed);if(start+compressed>offset)throw Error('ZIP data overlaps directory.');const src=data.subarray(start,start+compressed);const bytes=method===0?src:await inflate(src,expanded);if(bytes.length!==expanded||crc32(bytes)!==crc)throw Error('ZIP integrity check failed for '+name);if(!name.endsWith('/')){try{files[name]=dec.decode(bytes);}catch{throw Error('This builder reads text-only flow packages, not binary solution assets.');}}}if(pos!==offset+size)throw Error('ZIP directory length mismatch.');return files;}
root.FlowZip={store,read,crc32};
})(globalThis);
