(() => {
'use strict';
const $ = id => document.getElementById(id);
const data = JSON.parse($('knot-data').textContent);
const knots = data.knots;
const byId = new Map(knots.map(k=>[k.id,k]));
const essentials = ['overhand','figure-eight','square','sheet-bend','bowline','round-turn-two-half-hitches','clove-hitch','truckers-hitch'];
const levels = ['','Easy','Intermediate','Advanced'];
const KEY = 'misc-knotbook-v1';
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = s => String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,'').replace(/[-–]/g,' ');
let storageOK=true, state={saved:[],learned:[],large:false,images:true,all:false};
try {const old=JSON.parse(localStorage.getItem(KEY)||'null');if(old&&typeof old==='object'){for(const p of ['saved','learned'])if(Array.isArray(old[p]))state[p]=[...new Set(old[p].filter(id=>byId.has(id)))];for(const p of ['large','images','all'])if(typeof old[p]==='boolean')state[p]=old[p];}} catch(e){storageOK=false;}
let view='library', savedOnly=false, pathOnly=false, category='All knots', current=null, step=0, allSteps=state.all, libraryScroll=0, toastTimer;
const haystacks=new Map(knots.map(k=>[k.id,norm([k.name,k.summary,k.type,k.activities.join(' '),k.aliases.join(' ')].join(' '))]));
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;toast('This browser cannot save changes. Export your progress to keep it.');}updateCounts();}
function updateCounts(){ $('saved-count').textContent=state.saved.length;$('progress-count').textContent=state.learned.length+' / '+knots.length+' practiced';$('path-progress').textContent=essentials.filter(x=>state.learned.includes(x)).length+' of 8 practiced'; }
function placeholder(name){return '<div class="rope-placeholder"><div><span aria-hidden="true">⌘</span>'+esc(name)+'<br><small>Preview unavailable. Instructions are below.</small></div></div>';}
function picture(k,hero=false){if(!state.images||!k.video)return placeholder(k.name);return '<img src="https://i.ytimg.com/vi/'+esc(k.video)+'/hqdefault.jpg" alt="'+esc(k.name)+' tying demonstration preview" '+(hero?'fetchpriority="high"':'loading="lazy"')+' decoding="async" width="480" height="360">';}
function bindImageErrors(root){root.querySelectorAll('img').forEach(img=>{img.addEventListener('error',()=>{const p=document.createElement('div');p.className='rope-placeholder';p.textContent='Picture unavailable. Open the tutorial for written steps and source links.';img.replaceWith(p);},{once:true});});}
function renderHero(){const k=byId.get('bowline');$('hero-image').innerHTML=picture(k,true);bindImageErrors($('hero-image'));}
function renderChips(){const categories=['All knots','Everyday','Camping','Boating','Fishing','Decorative','Neckties','Specialist'];$('category-chips').innerHTML=categories.map(c=>'<button class="chip '+(c===category?'active':'')+'" aria-pressed="'+(c===category)+'" data-category="'+esc(c)+'">'+esc(c)+'</button>').join('');}
function card(k){const done=state.learned.includes(k.id),saved=state.saved.includes(k.id);return '<article class="card" data-id="'+k.id+'">'+(done?'<span class="practiced-tag">✓ PRACTICED</span>':'')+'<button class="card-save" data-save="'+k.id+'" aria-label="'+(saved?'Unsave ':'Save ')+esc(k.name)+'" aria-pressed="'+saved+'">'+(saved?'★':'☆')+'</button><a class="card-main" href="#knot/'+k.id+'"><div class="card-art">'+picture(k)+'<span class="media-type">'+(k.video?'▶ TYING DEMONSTRATION':'ILLUSTRATED SOURCE')+'</span></div><div class="card-content"><div class="meta"><span>'+esc(k.type.toUpperCase())+'</span><span>'+['','●','●●','●●●'][k.level]+' '+levels[k.level]+'</span></div><h3>'+esc(k.name)+'</h3><p class="summary">'+esc(k.summary)+'</p></div></a></article>';}
function filtered(){const q=norm($('search').value).trim().split(/\s+/).filter(Boolean),type=$('type').value,level=$('difficulty').value;let list=knots.filter(k=>(!savedOnly||state.saved.includes(k.id))&&(!pathOnly||essentials.includes(k.id))&&(category==='All knots'||k.activities.includes(category))&&(type==='all'||k.type===type)&&(level==='all'||k.level===Number(level))&&($('unlearned').getAttribute('aria-pressed')!=='true'||!state.learned.includes(k.id))&&q.every(term=>haystacks.get(k.id).includes(term)));
if(pathOnly)list.sort((a,b)=>essentials.indexOf(a.id)-essentials.indexOf(b.id));else if($('sort').value==='az')list.sort((a,b)=>a.name.localeCompare(b.name));else if($('sort').value==='easy')list.sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name));else list.sort((a,b)=>{const ai=essentials.indexOf(a.id),bi=essentials.indexOf(b.id);return (ai<0?999:ai)-(bi<0?999:bi)||a.name.localeCompare(b.name);});return list;}
function renderGrid(){const list=filtered();$('grid').innerHTML=list.map(card).join('');bindImageErrors($('grid'));$('results-count').textContent=list.length+' '+(list.length===1?'knot':'knots')+(savedOnly?' in your collection':' to explore');$('empty').hidden=!!list.length;$('empty-copy').textContent=savedOnly&&!state.saved.length?'Save a knot with the star on its card. Your collection will appear here.':'Try a broader search or reset your filters.';$('empty-reset').textContent=savedOnly&&!state.saved.length?'Explore the library':'Reset filters';$('library-title').textContent=savedOnly?'Your useful little collection.':pathOnly?'The essential eight.':'Find your next knot.';$('path-banner').hidden=!pathOnly;document.querySelector('.hero').hidden=savedOnly||pathOnly;updateCounts();renderChips();}
function clearFilters(){category='All knots';$('search').value='';$('type').value='all';$('difficulty').value='all';$('unlearned').setAttribute('aria-pressed','false');renderGrid();}
function toggleSave(id){const index=state.saved.indexOf(id);if(index<0)state.saved.push(id);else state.saved.splice(index,1);persist();renderGrid();if(current?.id===id)renderFlags();toast(index<0?'Saved to My knots.':'Removed from saved knots.');}
function setView(v,scroll=true){view=v;for(const id of ['library','basics','detail'])$(id+'-view').hidden=id!==v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',v==='basics'?b.dataset.view==='basics':b.dataset.view===(savedOnly?'saved':'library')));if(v!=='detail'){$('media').replaceChildren();current=null;document.title=v==='basics'?'Start here · Knotbook':savedOnly?'My knots · Knotbook':'Knotbook · A field guide to 100 knots';}if(scroll)window.scrollTo(0,0);}
function navigate(v){if(v==='basics')location.hash='basics';else if(v==='saved')location.hash='saved';else location.hash='';}
function route(){const h=location.hash.slice(1);if(h.startsWith('knot/')){const id=h.slice(5);if(byId.has(id)){if(view!=='detail')libraryScroll=window.scrollY;openKnot(id);return;}toast('That knot link was not found. Showing the library.');history.replaceState(null,'',location.pathname+location.search);}
if(h==='basics'){setView('basics');return;}savedOnly=h==='saved';pathOnly=h==='essentials';setView('library',false);renderGrid();if(savedOnly||pathOnly)window.scrollTo(0,0);else window.scrollTo(0,libraryScroll);}
function beginPath(){clearFilters();savedOnly=false;pathOnly=true;location.hash='essentials';if(view==='library'&&location.hash==='#essentials'){renderGrid();window.scrollTo(0,0);}}
function renderFlags(){if(!current)return;const saved=state.saved.includes(current.id),learned=state.learned.includes(current.id);$('detail-save').textContent=saved?'★ Saved':'☆ Save';$('detail-save').setAttribute('aria-pressed',String(saved));$('learned').textContent=learned?'✓ Practiced · tap to undo':'○ Mark as practiced';$('learned').setAttribute('aria-pressed',String(learned));}
function renderMedia(){const k=current;const available=!!k.video;$('media').innerHTML='<div class="poster">'+picture(k,true)+'</div>'+(available?'<button class="play-cover" id="play-video" aria-label="Play '+esc(k.name)+' tying demonstration"><span aria-hidden="true">▶</span><strong>Watch how it’s tied</strong></button>':'');bindImageErrors($('media'));$('youtube-link').hidden=!available;if(available){$('youtube-link').href='https://www.youtube.com/watch?v='+k.video;$('play-video').onclick=()=>{const frame=document.createElement('iframe');frame.title=k.name+' tying demonstration by Animated Knots by Grog';frame.src='https://www.youtube-nocookie.com/embed/'+k.video+'?autoplay=1&playsinline=1&rel=0';frame.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';$('play-video').remove();$('media').append(frame);};}$('source-link').href=k.source;}
function stepParts(s){const at=s.indexOf('::');return at>=0?[s.slice(0,at),s.slice(at+2)]:['Step '+(step+1),s];}
function renderSteps(){if(!current)return;const n=current.steps.length;$('step-position').textContent=allSteps?n+' steps, at your own pace':'STEP '+(step+1)+' OF '+n;$('step-dots').innerHTML=current.steps.map((s,i)=>'<button class="'+(i===step?'active':'')+'" data-step="'+i+'" aria-label="Go to step '+(i+1)+'" '+(i===step?'aria-current="step"':'')+'></button>').join('');$('steps').classList.toggle('all',allSteps);$('steps').innerHTML=current.steps.map((s,i)=>{const [title,text]=stepParts(s);return '<article class="step" '+(!allSteps&&i!==step?'hidden':'')+'><span class="step-number">'+String(i+1).padStart(2,'0')+'</span><h3>'+esc(title)+'</h3><p>'+esc(text)+'</p></article>';}).join('');$('prev-step').disabled=step===0;$('next-step').disabled=step===n-1;$('next-step').textContent=step===n-1?'Sequence complete ✓':'Next step →';$('show-all').textContent=allSteps?'One step at a time':'Show all steps';$('show-all').setAttribute('aria-pressed',String(allSteps));document.querySelector('.step-controls').hidden=allSteps;}
function openKnot(id){current=byId.get(id);step=0;allSteps=state.all;setView('detail');const k=current;document.title=k.name+' · Knotbook';$('detail-eyebrow').textContent=k.type.toUpperCase()+' / '+k.activities.join(' + ').toUpperCase();$('knot-title').textContent=k.name;$('knot-summary').textContent=k.summary;$('aliases').textContent=k.aliases.length?'Also called '+k.aliases.join(' · '):'';$('detail-level').textContent=levels[k.level]+' · '+k.steps.length+' steps';$('materials').textContent=k.materials;$('check').textContent=k.check;$('mistake').textContent=k.mistake;$('detail-warning').innerHTML='<strong>Know the limits.</strong>'+esc(k.caution)+'<br><small>Learning only. Not a substitute for qualified instruction or rated equipment.</small>';renderMedia();renderSteps();renderFlags();let rel=knots.filter(x=>x.id!==id&&x.type===k.type);if(rel.length<3)rel=rel.concat(knots.filter(x=>x.id!==id&&!rel.includes(x)&&x.activities.some(a=>k.activities.includes(a))));$('related').innerHTML=rel.slice(0,3).map(x=>'<a class="related-card" href="#knot/'+x.id+'"><small>'+esc(x.type)+' · '+levels[x.level]+'</small><strong>'+esc(x.name)+' ↗</strong></a>').join('');$('knot-title').focus({preventScroll:true});}
function applyPreferences(){document.body.classList.toggle('large-type',state.large);$('large-type').checked=state.large;$('load-images').checked=state.images;$('all-default').checked=state.all;renderHero();renderGrid();if(current){allSteps=state.all;renderSteps();renderMedia();}}
// Event delegation keeps the 100-card library lightweight.
$('grid').addEventListener('click',e=>{const b=e.target.closest('[data-save]');if(b){e.preventDefault();toggleSave(b.dataset.save);}});
$('category-chips').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;renderGrid();}});
$('step-dots').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b){step=Number(b.dataset.step);allSteps=false;renderSteps();}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
$('search').addEventListener('input',renderGrid);$('search').addEventListener('keydown',e=>{if(e.key==='Enter')$('search').blur();});
for(const id of ['type','difficulty','sort'])$(id).addEventListener('change',renderGrid);
$('unlearned').onclick=()=>{$('unlearned').setAttribute('aria-pressed',String($('unlearned').getAttribute('aria-pressed')!=='true'));renderGrid();};
$('clear').onclick=clearFilters;$('empty-reset').onclick=()=>{clearFilters();if(savedOnly&&!state.saved.length)navigate('library');};
$('beginner-btn').onclick=beginPath;$('primer-start').onclick=beginPath;$('end-path').onclick=()=>{pathOnly=false;clearFilters();navigate('library');};
$('back').onclick=()=>{location.hash=savedOnly?'saved':pathOnly?'essentials':'';};
$('detail-save').onclick=()=>current&&toggleSave(current.id);
$('learned').onclick=()=>{if(!current)return;const i=state.learned.indexOf(current.id);if(i<0)state.learned.push(current.id);else state.learned.splice(i,1);persist();renderFlags();toast(i<0?'Practice recorded. Try tying it again from memory.':'Practice marker removed.');};
$('prev-step').onclick=()=>{if(step>0){step--;renderSteps();}};$('next-step').onclick=()=>{if(current&&step<current.steps.length-1){step++;renderSteps();}};
$('show-all').onclick=()=>{allSteps=!allSteps;renderSteps();};
$('random-knot').onclick=()=>{const list=knots.filter(k=>k.id!==current?.id);location.hash='knot/'+list[Math.floor(Math.random()*list.length)].id;};
$('print').onclick=()=>window.print();
$('share').onclick=async()=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(location.href);toast('Knot link copied.');}catch(e){window.prompt('Copy this knot link:',location.href);}};
$('settings-btn').onclick=()=>{$('settings').showModal();};
$('settings').addEventListener('click',e=>{if(e.target===$('settings')){const r=$('settings').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('settings').close();}});
for(const [id,prop] of [['large-type','large'],['load-images','images'],['all-default','all']])$(id).onchange=()=>{state[prop]=$(id).checked;persist();applyPreferences();};
$('export-progress').onclick=()=>{const blob=new Blob([JSON.stringify({app:'knotbook',version:1,exported:new Date().toISOString(),...state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='knotbook-progress.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import-progress').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>100000)throw Error('File is too large.');const imported=JSON.parse(await file.text());if(imported.app!=='knotbook'||imported.version!==1||!Array.isArray(imported.saved)||!Array.isArray(imported.learned))throw Error('Choose a Knotbook progress export.');for(const key of ['saved','learned'])state[key]=[...new Set([...state[key],...imported[key].filter(id=>typeof id==='string'&&byId.has(id))])];persist();applyPreferences();if(current)renderFlags();toast('Progress merged. Existing marks were kept.');}catch(err){toast(err.message||'Unable to read that progress file.');}};
$('reset-progress').onclick=()=>{if(confirm('Clear all saved knots and practice records from this browser? Export first to keep a backup.')){state.saved=[];state.learned=[];persist();renderGrid();renderFlags();toast('Saved knots and practice records cleared.');}};
document.addEventListener('keydown',e=>{if($('settings').open||e.target.closest('input,textarea,select,iframe,[contenteditable=true]'))return;if(e.key==='/'){e.preventDefault();if(view!=='library'){navigate('library');setTimeout(()=>$('search').focus(),0);}else $('search').focus();}if(view==='detail'){if(e.key==='ArrowRight'&&!allSteps){e.preventDefault();$('next-step').click();}if(e.key==='ArrowLeft'&&!allSteps){e.preventDefault();$('prev-step').click();}if(e.key==='Escape')$('back').click();}});
window.addEventListener('hashchange',route);
$('type').insertAdjacentHTML('beforeend',[...new Set(knots.map(k=>k.type))].sort().map(t=>'<option value="'+esc(t)+'">'+esc(t)+'</option>').join(''));
$('total-count').textContent=knots.length;
applyPreferences();route();
if(!storageOK)toast('Browser storage is unavailable. Use Export progress to keep your practice record.');
// Narrow, read-only test hook: never expose a mutation API or any user information.
Object.defineProperty(window,'Knotbook',{value:Object.freeze({version:'1.0.0',count:knots.length,ids:Object.freeze(knots.map(k=>k.id))}),writable:false});
})();
