/* Knotbook original rope-path diagrams, batch 1. No images, video or runtime dependencies.
   Points are hand-authored x,y,depth waypoints, not traced photographs. Larger depth is nearer.
   Each move extends a rope path; this is an instructional schematic, not a rope-physics model. */
(() => {
'use strict';
const NS='http://www.w3.org/2000/svg', BG='#f0f3ec', INK='#173f39';
const colors=['#d57632','#367aa0'], edges=['#86421d','#214e68'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pts=s=>s.trim().split(/\s+/).map(v=>{const a=v.split(',').map(Number);return [a[0],a[1],a[2]||0];});
const D={};
const rope=(points,cuts,color=0)=>({points:typeof points==='string'?pts(points):points,cuts,color});
const add=(id,ropes,moves,notes,extra={})=>{D[id]={id,ropes,moves,notes,...extra};};
// An open trefoil, with three alternating crossings and a generous visible tail.
const O=pts('65,220 200,220 380,220 505,220 520,305 445,355 320,355 240,295 250,220,35 275,145,30 345,100 420,145,-25 420,220,-35 410,285 395,350,35 435,400,35');
// A second passage through the SAME eye, before the tail leaves the large lower loop.
const DO=O.slice(0,14).concat(pts('350,285,35 330,220,35 345,165,25 385,170,-25 380,220,-35 375,290 365,350,35 420,400,35'));
// Go behind the standing part OUTSIDE the first loop, then return through that loop.
const F=O.slice(0,9).concat(pts('215,145,30 145,140 130,220,-35 175,290,-25 245,300,35 320,300,30 390,350,-35 455,400,-35'));
const ST=F.slice(0,13).concat(pts('210,280,35 220,220,35 205,175,25 170,185,-25 175,220,-35 215,310,-25 275,310,35 340,310,25 420,350,-35 480,400,-35'));
add('overhand',[rope(O,[3,9,15,15,15])],['Find the working end','Make the crossing loop','Pass the whole tail through','Draw out the slack','Inspect the stopper'],['S is the standing part. Move the marked tip.','The returning strand crosses OVER the standing part.','Take the end behind the upper strand, through the eye and out.','Pull standing part and tail apart. The diagram stays loose for visibility.','One pass through the eye. Leave a visible tail; do not jam it.']);
add('double-overhand',[rope(DO,[9,13,21,21,21])],['Make a loose loop','Pass through once','Pass through again','Arrange the two turns','Snug the stopper'],['Leave more tail than for a plain overhand.','First passage: do not tighten yet.','Use the SAME opening a second time, not a separate overhand knot.','Keep the two turns beside each other.','Pull standing part and tail apart to form the barrel.']);
add('figure-eight',[rope(F,[9,12,14,16,16])],['Make the first loop','Go behind the standing part','Come back toward the eye','Thread through the first loop','Dress the figure eight'],['The tail crosses over the standing part.','Go around the standing part outside the large loop.','Bring the tail back toward the original opening.','Enter the original eye after going around the standing part.','Arrange the two lobes and keep a visible tail.']);
add('stevedore',[rope(ST,[7,9,18,22,22])],['Leave a large bight','Cross the standing part','Make two complete turns','Return through the bight','Dress the stopper'],['Keep the original lower opening loose.','Begin winding around the standing section.','One extra full turn compared with a figure eight.','The end returns through the original large opening.','Arrange adjacent turns before pulling the ends apart.']);
const SL=O.slice(0,14).concat(pts('385,355,35 370,395,35 425,405,35 455,355,35 455,290 465,230,-35 490,205,-35 550,175,-35'));
add('slip-knot',[rope(SL,[9,10,21,21,21])],['Make an overhand loop','Fold the SHORT end','Pass the folded section through','Snug around the fold','Check the release tail'],['Keep the short tail available.','Use a bight from the working end, not the standing part.','The lower U is a folded bight. Do not pull the whole tail through.','The knot grips the two legs of the bight.','Pull the free tail to withdraw the bight, while unloaded.'],{foldNote:true});
// Opposed bights: A's two exits remain on the left, B's on the right.
const SQa=pts('60,270,-35 250,270,-35 425,335,-35 470,235,35 425,135,35 305,195,35 185,105,35');
const SQb=pts('580,270 390,270 215,335 170,235 215,135 335,195 455,105');
add('square',[rope(SQa,[1,3,4,6,6]),rope(SQb,[1,3,4,6,6],1)],['Cross right over left','Make the first half knot','Reverse the crossing','Complete the second half knot','Flatten and inspect'],['Use the two ends around the same bundle.','Tuck under and draw the first half knot together.','Reverse the handedness; do not repeat a granny knot.','Bring the same colored end over its partner again.','Both gold exits are on one side; both blue exits on the other. Binding only.']);
const SBb=pts('65,270 250,270 435,270 470,215 425,145 310,165 195,130');
const SBa=pts('570,335 515,295,-25 425,230,-25 350,210,35 265,195,35 255,135,-35 210,210,-35 260,310,-35 355,315 395,260,10 365,195,10 340,115,10');
add('sheet-bend',[rope(SBb,[6,6,6,6,6],1),rope(SBa,[0,4,8,11,11])],['Fold the thicker rope','Bring the thin end through','Go behind BOTH legs','Tuck beneath itself','Check the tail exits'],['Blue is the thicker or stiffer rope, folded into a U.','Bring gold from behind the blue eye to its front.','Circle the blue tail first, then its standing part.','Tuck gold under its earlier gold section, not back through the blue eye.','The short blue tail and gold tail must leave on the same side.']);
const BOW=pts('305,45 305,100 305,185 355,225 420,205 435,150 385,120 330,135 305,185,40 280,250,40 235,335 290,400 460,375 485,280 425,230,-30 385,185,-30 365,150,35 345,100,35 305,80,-35 255,100,-20 260,145,35 305,160,35 350,180,20 380,225,-25 380,285,-25');
add('bowline',[rope(BOW,[9,16,21,24,24])],['Make the small crossing loop','Bring the end up through','Go around the standing part','Return through the small loop','Dress the collar'],['The upper opening is the small loop. Leave rope for the big eye.','Make the large lower eye, then pass its end up through the small loop.','Go behind S, the standing part. Do not circle a leg of the large eye.','Return down through the original small opening beside the first pass.','The tail belongs inside the large eye. The collar wraps the standing part.']);
// Horizontal practice bar. Negative depth indicates the back of the bar.
const CL=pts('225,395,30 265,300,30 270,200,35 270,100 240,100,-45 240,200,-55 245,295,65 305,250,65 375,160,65 405,95 430,110,-45 430,200,-55 420,295 380,260,35 340,200,20 325,130,20 325,60,20');
add('clove-hitch',[rope(CL,[6,9,12,16,16])],['Wrap the bar once','Cross over the first turn','Go around again','Tuck under the diagonal','Set the adjacent turns'],['Dotted rope is behind the bar.','The diagonal goes over the first front turn.','The second wrap goes around in the same direction.','The tail passes UNDER the diagonal riding section.','Pull the ends apart. A clove hitch can slip or bind.'],{bar:true});
const COW=CL.slice(0,7).concat(pts('310,305,55 390,305,55 420,255 420,170,-55 420,100,-45 390,100 380,200,35 365,305,20 335,350,20 305,395,20'));
add('cow-hitch',[rope(COW,[6,8,12,16,16])],['Make the first turn','Cross the standing part','Reverse around the bar','Pass under the connector','Set both ends together'],['One turn over the bar and back underneath.','The linking section runs across the front.','The second turn runs in the OPPOSITE direction to the first.','Bring the tail under the linking section between the turns.','Both ends leave below the bar. Unequal loading can loosen it.'],{bar:true});
const hs=(u,v,z=0)=>[330-.8*u+.6*v,260+.6*u+.8*v,z];
const hturn=(u=0)=>[[30,45,35],[35,0,50],[55,-25,0],[80,0,-40],[60,35,0],[30,20,10]].map(p=>hs(p[0]+u,p[1],p[2]));
const post=pts('170,380,30 250,320,30 330,260,30 330,195,35 330,100 370,100,-45 370,195,-55 355,270');
const HH=post.concat(hturn());
add('half-hitch',[rope(HH,[7,9,13,13,13])],['Go around the object','Cross the standing part','Go behind and through','Snug lightly','Learn the limitation'],['Bring the working end back toward S.','Take the tail across the standing part.','Wrap around the standing part and through its own opening.','Pull the tail only enough to make the crossing clear.','A single half hitch is not a secure standalone attachment.'],{bar:true});
const RT=post.concat(pts('405,265,35 425,195,35 425,100 465,100,-45 465,195,-55 440,285'),hturn(),[hs(20,65,25),hs(110,65,25)],hturn(90));
add('round-turn-two-half-hitches',[rope(RT,[7,13,19,27,27])],['Go around the bar','Add the round turn','Make the first half hitch','Repeat in the same direction','Dress the paired hitches'],['A single turn returns toward the standing part.','Go around again before starting the hitches.','Tie a half hitch around S, not around the bar.','Make another half hitch with the same handedness.','Slide the hitches together and leave a generous tail.'],{bar:true});
const CON=CL.slice(0,13).concat(pts('370,300,45 300,265,55 250,220,55 290,160,20 340,205,10 385,245,10 415,205,20 410,80,20'));
add('constrictor',[rope(CON,[9,12,15,20,20])],['Wrap and cross','Make the second turn','Cross the standing section','Go under the riding turn','Set the binding'],['Start with a wrap and a diagonal crossing.','Lay the second turn next to the first.','The tail crosses the standing section before the final tuck.','Trap that crossing under the diagonal riding turn.','Use only on a practice bundle. It may jam permanently.'],{bar:true});
const STR=pts('210,395,30 270,300,30 290,200,35 290,100 250,100,-45 250,200,-55 250,295 335,280,55 375,200,55 385,100 420,100,-45 420,200,-55 420,295 440,320,30 435,240,15 390,200,10 330,200,10 270,180,10 240,90,10');
add('strangle',[rope(STR,[6,12,13,18,18])],['Make the first turn','Wrap a second time','Keep a passage open','Go under BOTH turns','Tighten the binding'],['Wrap the object once.','Continue around again in the same direction.','Keep the original two turns loose.','The final tail passes underneath both turns together.','Arrange the coils. This binding can be difficult to undo.'],{bar:true});
const TIM=pts('185,400,30 265,310,30 320,205,35 320,100 365,100,-45 365,195,-55 355,270').concat(pts('320,300,55 255,310,55 225,350 275,360,-30 305,315,-30 325,280,40 365,270,45 390,285 360,300,-25 340,275,-25 375,240,45 405,240,45 410,260 380,275,-25 375,250,-25 400,215,45 430,220,45 430,245 405,250,-25'));
add('timber-hitch',[rope(TIM,[6,11,15,25,25])],['Go around the timber','Circle the standing part','Turn back on the returning section','Make at least three tucks','Seat against the timber'],['Use a small unloaded practice pole.','Take the working end around S once.','Twist around the returning rope, not around S again.','Three are shown. Rope and timber size may require more.','Tension grips the tucked section; slack can release the hitch.'],{bar:true});
// Parallel-strand operations use normal offsets, not independent generic loop drawings.
function offset(p,d){return p.map((v,i)=>{const a=p[Math.max(0,i-1)],b=p[Math.min(p.length-1,i+1)],dx=b[0]-a[0],dy=b[1]-a[1],l=Math.hypot(dx,dy)||1;return [v[0]-dy/l*d,v[1]+dx/l*d,v[2]];});}
const paired=(p,cuts,same=false)=>[rope(offset(p,-9),cuts,0),rope(offset(p,9),cuts,same?0:1)];
add('flat-overhand-bend',paired(O,[3,9,15,15,15]),['Align the two tails','Make one shared loop','Pass BOTH tails through','Dress the paired strands','Set each of the four parts'],['Both tails point the same way. Both standing parts are at S.','Treat both ropes as one doubled strand.','One pass only. Keep the two tails together.','Remove loose pockets without crossing the paired strands.','Practice only. Tail length, material and loading require qualified instruction.'],{pair:true});
add('surgeons-join',paired(DO,[3,9,13,21,21]),['Overlap the lines','Make one shared loop','Pass the pair through once','Repeat through the same opening','Set all four sections'],['Leader and main line point in opposite directions.','Treat the overlapped section as one strand.','Carry the whole short leader through with the other tag.','Take the SAME pair through the original eye a second time.','Moisten fishing line as appropriate. Tighten and inspect all four sections.'],{pair:true,leader:true});
add('surgeons-loop',paired(DO,[3,9,13,21,21],true),['Double the line','Make an overhand opening','Pass the bight once','Pass the bight again','Set the fixed eye'],['The joined tips form a bight in ONE line.','Keep both legs beside one another.','Push the folded end through, not the separate free ends.','Pass the same fold through the same opening a second time.','Adjust the eye, moisten fishing line, then draw both legs and the eye snug.'],{pair:true,folded:true});
function retrace(id,p,moves,notes,webbing=false){const back=offset(p,18).reverse();add(id,[rope(p,[p.length-1,p.length-1,p.length-1,p.length-1,p.length-1]),rope(back,[0,3,p.length-1,p.length-1,p.length-1],1)],moves,notes,{retrace:true,webbing});}
retrace('water-knot',O,['Start with a loose overhand','Enter beside the first tail','Retrace every turn backward','Smooth the webbing','Set and inspect both tails'],['Gold is a flat strip with a loose overhand already tied.','Blue begins beside the gold tail and travels in the reverse direction.','Follow the whole gold path, keeping the strips alongside each other.','The broad faces must remain flat. Do not introduce a twist.','Tails can creep in use. Leave generous tails and recheck them.'],true);
retrace('figure-eight-bend',F,['Start with a loose figure eight','Enter from the first tail','Retrace the entire eight','Keep the two paths parallel','Set all four parts'],['Gold is a loose figure eight. Its openings remain visible.','Introduce blue beside the gold tail.','Follow the gold strand backward through both lobes.','Work out crossed or stacked strands before snugging.','Pull each standing part and tail individually. Not a qualification for loaded use.']);

// Geometry is computed once per diagram and reused by the frame player.
function sample(nodes){const out=[];for(let i=0;i<nodes.length-1;i++){const p0=nodes[Math.max(0,i-1)],p1=nodes[i],p2=nodes[i+1],p3=nodes[Math.min(nodes.length-1,i+2)];for(let j=0;j<16;j++){const t=j/16,t2=t*t,t3=t2*t;out.push([0,1,2].map(k=>.5*((2*p1[k])+(-p0[k]+p2[k])*t+(2*p0[k]-5*p1[k]+4*p2[k]-p3[k])*t2+(-p0[k]+3*p1[k]-3*p2[k]+p3[k])*t3)));}}out.push(nodes.at(-1));return out;}
function path(p){return p.length?'M'+p.map(v=>v[0].toFixed(1)+','+v[1].toFixed(1)).join('L'):'';}
function hit(a,b,c,d){const ux=b[0]-a[0],uy=b[1]-a[1],vx=d[0]-c[0],vy=d[1]-c[1],det=ux*vy-uy*vx;if(Math.abs(det)<1e-7)return null;const dx=c[0]-a[0],dy=c[1]-a[1],t=(dx*vy-dy*vx)/det,u=(dx*uy-dy*ux)/det;return t>=0&&t<1&&u>=0&&u<1?{t,u}:null;}
function prepare(def){if(def.cache)return def.cache;const ropes=def.ropes.map(r=>({...r,p:sample(r.points)}));const crosses=[];for(let a=0;a<ropes.length;a++)for(let b=a;b<ropes.length;b++){const p=ropes[a].p,q=ropes[b].p;for(let i=0;i<p.length-1;i++)for(let j=a===b?i+8:0;j<q.length-1;j++){const h=hit(p[i],p[i+1],q[j],q[j+1]);if(!h)continue;const za=p[i][2]+h.t*(p[i+1][2]-p[i][2]),zb=q[j][2]+h.u*(q[j+1][2]-q[j][2]);crosses.push({a,b,i,j,top:za>zb?a:b,at:za>zb?i+h.t:j+h.u,z:Math.max(za,zb),gap:Math.abs(za-zb)});}}crosses.sort((a,b)=>a.z-b.z);return def.cache={ropes,crosses};}
const stroke=(p,c,w,extra='')=>'<path d="'+path(p)+'" fill="none" stroke="'+c+'" stroke-width="'+w+'" stroke-linecap="round" stroke-linejoin="round" '+extra+'/>';
function body(p,c,w,flat=false){return stroke(p,edges[c],w+3)+stroke(p,colors[c],w)+(flat?'':stroke(p,'#fff4da',2,'opacity=".48" stroke-dasharray="2 9"'));}
function picture(id,stage=4,progress=1,mirror=false,compact=false){const def=D[id];if(!def)return '';const {ropes,crosses}=prepare(def);const w=def.pair?9:def.webbing?13:13;const visible=ropes.map(r=>{const to=Math.min(r.cuts[stage],r.points.length-1)*16,from=stage?Math.min(r.cuts[stage-1],r.points.length-1)*16:0;return Math.max(1,Math.min(r.p.length,Math.round(from+(to-from)*progress)+1));});const transform=mirror?'translate(640 0) scale(-1 1)':'';
let s='<svg xmlns="'+NS+'" viewBox="0 0 640 440" role="img" aria-label="'+esc(id.replaceAll('-',' ')+' original rope-path diagram, move '+(stage+1))+'"><rect width="640" height="440" rx="20" fill="'+BG+'"/><g transform="'+transform+'">';
if(!compact){for(let x=35;x<640;x+=32)for(let y=40;y<420;y+=32)s+='<circle cx="'+x+'" cy="'+y+'" r="1" fill="#173f39" opacity=".07"/>';}
if(def.bar)s+='<rect x="38" y="140" width="564" height="100" rx="16" fill="#dcc8a8" stroke="#b69e7d" stroke-width="2"/><path d="M55 162H585M55 218H585" stroke="#b69e7d" stroke-width="2" opacity=".55"/>';
// Pale preview contains ONLY this move, never a pre-revealed finished knot.
ropes.forEach((r,i)=>{const start=stage?r.cuts[stage-1]*16:0,end=Math.min(r.cuts[stage]*16,r.p.length-1);if(!compact&&progress<1&&end>start)s+=stroke(r.p.slice(start,end+1),colors[r.color],w,'opacity=".16" stroke-dasharray="5 9"');s+=body(r.p.slice(0,visible[i]),r.color,w,def.webbing);});
if(def.bar){s+='<rect x="40" y="142" width="560" height="96" rx="14" fill="#dcc8a8" opacity=".9"/>';ropes.forEach((r,i)=>{let run=[];for(let j=0;j<visible[i];j++){const p=r.p[j],front=p[2]>=0||p[1]<138||p[1]>242;if(front){run.push(p);}else{if(run.length>1)s+=body(run,r.color,w);run=[];}}if(run.length>1)s+=body(run,r.color,w);let back=[];for(let j=0;j<visible[i];j++){const p=r.p[j];if(p[2]<0&&p[1]>=138&&p[1]<=242)back.push(p);else{if(back.length>1)s+=stroke(back,edges[r.color],5,'opacity=".6" stroke-dasharray="5 7"');back=[];}}if(back.length>1)s+=stroke(back,edges[r.color],5,'opacity=".6" stroke-dasharray="5 7"');});}
for(const x of crosses){if(x.i>=visible[x.a]-1||x.j>=visible[x.b]-1)continue;const r=ropes[x.top],a=Math.max(0,Math.floor(x.at)-4),b=Math.min(visible[x.top],Math.ceil(x.at)+6),p=r.p.slice(a,b);if(def.bar&&x.z<0)continue;s+=stroke(p,def.bar&&p.some(v=>v[1]>140&&v[1]<240)?'#dcc8a8':BG,w+10)+body(p,r.color,w,def.webbing);}
if(def.folded){const a=ropes[0].p[visible[0]-1],b=ropes[1].p[visible[1]-1],prior=ropes[0].p[Math.max(0,visible[0]-4)],dx=a[0]-prior[0],dy=a[1]-prior[1],len=Math.hypot(dx,dy)||1;const d='M'+a[0]+','+a[1]+'Q'+((a[0]+b[0])/2+dx/len*28)+','+((a[1]+b[1])/2+dy/len*28)+' '+b[0]+','+b[1];s+='<path d="'+d+'" fill="none" stroke="'+edges[0]+'" stroke-width="12"/><path d="'+d+'" fill="none" stroke="'+colors[0]+'" stroke-width="9"/>';}
// The working tip is a dot; S identifies the fixed beginning.
if(!compact){ropes.forEach((r,i)=>{const p=r.p[visible[i]-1];if(def.retrace&&i===0)return;if(def.folded&&i===1)return;s+='<circle cx="'+p[0]+'" cy="'+p[1]+'" r="11" fill="'+INK+'" stroke="white" stroke-width="3"/>';});}
s+='</g>';
if(!compact&&!def.leader){const a=ropes[0].p[0],x=mirror?640-a[0]:a[0];s+='<text x="'+x+'" y="'+Math.max(22,a[1]-21)+'" text-anchor="middle" fill="'+INK+'" font-size="16" font-family="system-ui" font-weight="700">S</text><text x="24" y="29" fill="'+INK+'" font-size="13" font-family="system-ui" letter-spacing="2">MOVE '+String(stage+1).padStart(2,'0')+'</text>';if(def.bar)s+='<text x="610" y="29" text-anchor="end" fill="'+INK+'" font-size="12" font-family="system-ui">Dotted = behind the bar</text>';}
if(!compact&&def.leader)s+='<text x="24" y="197" fill="'+INK+'" font-size="12" font-family="system-ui">Gold: standing / Blue: tag</text><text x="310" y="429" fill="'+INK+'" font-size="12" font-family="system-ui">Gold: tag / Blue: leader</text>';
return s+'</svg>';}
const thumbs=new Map();
let active=null;
function stop(){if(!active)return;cancelAnimationFrame(active.raf);active.root.classList.remove('oa-expanded','original-media');active.root.onkeydown=null;delete active.root.dataset.animation;delete active.root.dataset.move;delete active.root.dataset.progress;document.body.classList.remove('oa-no-scroll');active=null;}
function mount(root,k,onStep){stop();const def=D[k.id];if(!def)return;root.classList.add('original-media');root.innerHTML='<div class="oa-head"><span>ORIGINAL ANIMATION <b>01 / 05</b></span><button type="button" id="oa-expand" aria-label="Enlarge animation">Enlarge</button></div><div id="oa-stage"></div><div class="oa-caption"><strong id="oa-title"></strong><p id="oa-note"></p></div><div class="oa-controls"><button id="oa-prev" type="button" aria-label="Previous animation move">←</button><button id="oa-play" type="button">▶ Play moves</button><button id="oa-next" type="button" aria-label="Next animation move">→</button><button id="oa-replay" type="button" aria-label="Replay this move">↻</button></div><label class="oa-scrub">Whole sequence<input id="oa-scrub" type="range" min="0" max="1000" value="0" aria-label="Animation timeline"></label><div class="oa-options"><label>Speed <select id="oa-speed" aria-label="Animation speed"><option value="0.5">Slow</option><option value="1" selected>Normal</option><option value="1.5">Fast</option></select></label><button id="oa-mirror" type="button" aria-pressed="false">Mirror</button><label><input id="oa-loop" type="checkbox"> Repeat</label></div><p class="oa-hint">Follow the moving dot. Pale dashes show the next route. Rope-path schematic, not a physics simulation. Spacing is expanded for inspection.</p><div class="oa-print" aria-hidden="true"></div>';
active={root,k,def,onStep,stage:0,progress:1,playing:false,mirror:false,speed:1,last:0,raf:0,hold:0};const a=active,$=id=>root.querySelector('#'+id);
function show(){if(active!==a)return;const paintKey=a.stage+':'+a.progress.toFixed(3)+':'+a.mirror;if(a.paintKey!==paintKey){$('oa-stage').innerHTML=picture(k.id,a.stage,a.progress,a.mirror);a.paintKey=paintKey;}$('oa-title').textContent=def.moves[a.stage];$('oa-note').textContent=def.notes[a.stage];root.querySelector('.oa-head b').textContent=String(a.stage+1).padStart(2,'0')+' / 05';$('oa-prev').disabled=a.stage===0;$('oa-next').disabled=a.stage===4;$('oa-scrub').value=Math.round((a.stage+a.progress)/5*1000);$('oa-play').textContent=a.playing?'Ⅱ Pause':a.stage===4&&a.progress>=1?'↻ Play again':'▶ Play moves';root.dataset.animation=k.id;root.dataset.move=String(a.stage);root.dataset.progress=a.progress.toFixed(3);}
function frame(now){if(active!==a||!a.playing)return;const dt=Math.min(80,now-(a.last||now));a.last=now;if(a.progress<1){a.progress=Math.min(1,a.progress+dt*a.speed/2600);a.hold=0;}else{a.hold+=dt*a.speed;if(a.hold>=1800){if(a.stage<4){a.stage++;a.progress=0;a.hold=0;a.onStep(a.stage);}else if($('oa-loop').checked){a.stage=0;a.progress=0;a.hold=0;a.onStep(0);}else a.playing=false;}}show();if(a.playing)a.raf=requestAnimationFrame(frame);}
function play(){if(a.stage===4&&a.progress===1){a.stage=0;a.progress=0;a.onStep(0);}else if(!a.playing&&a.progress>=1){a.progress=0;}a.playing=!a.playing;a.last=0;cancelAnimationFrame(a.raf);show();if(a.playing)a.raf=requestAnimationFrame(frame);}
a.show=show;a.pause=()=>{a.playing=false;cancelAnimationFrame(a.raf);show();};a.select=(n,progress=1)=>{a.stage=Math.max(0,Math.min(4,n));a.progress=progress;a.hold=0;a.last=0;show();};
$('oa-play').onclick=play;$('oa-prev').onclick=()=>{a.pause();a.select(a.stage-1);a.onStep(a.stage);};$('oa-next').onclick=()=>{a.pause();a.select(a.stage+1);a.onStep(a.stage);};$('oa-replay').onclick=()=>{a.pause();a.progress=0;a.playing=true;a.last=0;show();a.raf=requestAnimationFrame(frame);};$('oa-speed').onchange=e=>{a.speed=Number(e.target.value);};$('oa-mirror').onclick=e=>{a.mirror=!a.mirror;e.currentTarget.setAttribute('aria-pressed',a.mirror);show();};$('oa-scrub').oninput=e=>{const v=Number(e.target.value)/200,n=Math.min(4,Math.floor(v));a.pause();a.select(n,v===5?1:v-n);a.onStep(n);};$('oa-expand').onclick=()=>{const expanded=root.classList.toggle('oa-expanded');document.body.classList.toggle('oa-no-scroll',expanded);$('oa-expand').setAttribute('aria-expanded',String(expanded));$('oa-expand').focus();$('oa-expand').textContent=expanded?'Close large view':'Enlarge';};
root.onkeydown=e=>{if(e.key==='Escape'&&root.classList.contains('oa-expanded')){e.preventDefault();e.stopPropagation();$('oa-expand').click();}if(e.key==='Tab'&&root.classList.contains('oa-expanded')){const f=[...root.querySelectorAll('button:not(:disabled),input,select,[tabindex="0"]')];if(e.shiftKey&&e.target===f[0]){e.preventDefault();f.at(-1).focus();}else if(!e.shiftKey&&e.target===f.at(-1)){e.preventDefault();f[0].focus();}}if(e.code==='Space'&&e.target===$('oa-stage')){e.preventDefault();play();}};$('oa-stage').tabIndex=0;$('oa-stage').setAttribute('aria-label','Animation diagram. Space plays or pauses.');
root.querySelector('.oa-print').innerHTML=def.moves.map((m,i)=>'<figure>'+picture(k.id,i,1,false,true)+'<figcaption>'+String(i+1)+'. '+esc(m)+'</figcaption></figure>').join('');show();}
function sync(id,n){if(active?.k.id===id&&active.stage!==n){active.pause();active.select(n);}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)active?.pause();});
window.KnotOriginals=Object.freeze({ids:Object.freeze(Object.keys(D)),has:id=>!!D[id],picture,mount,sync,stop,thumbnail(id){if(!thumbs.has(id))thumbs.set(id,picture(id,4,1,false,true));return thumbs.get(id);},inspect:id=>{const d=D[id],c=prepare(d);return {id,stages:d.moves.length,ropes:d.ropes.length,points:d.ropes.map(r=>r.points.length),cuts:d.ropes.map(r=>r.cuts),crossings:c.crosses.map(x=>({gap:x.gap,top:x.top,at:x.at})),bounds:c.ropes.flatMap(r=>r.p).reduce((v,p)=>[Math.min(v[0],p[0]),Math.min(v[1],p[1]),Math.max(v[2],p[0]),Math.max(v[3],p[1])],[Infinity,Infinity,-Infinity,-Infinity])};}});
})();
